// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: encore/parser/schema/v1/schema.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Builtin represents a type which Encore (and Go) have inbuilt support for and so can be represented by Encore's tooling
// directly, rather than needing to understand the full implementation details of how the type is structured.
type Builtin int32

const (
	// Inbuilt Go Types
	Builtin_ANY     Builtin = 0
	Builtin_BOOL    Builtin = 1
	Builtin_INT8    Builtin = 2
	Builtin_INT16   Builtin = 3
	Builtin_INT32   Builtin = 4
	Builtin_INT64   Builtin = 5
	Builtin_UINT8   Builtin = 6
	Builtin_UINT16  Builtin = 7
	Builtin_UINT32  Builtin = 8
	Builtin_UINT64  Builtin = 9
	Builtin_FLOAT32 Builtin = 10
	Builtin_FLOAT64 Builtin = 11
	Builtin_STRING  Builtin = 12
	Builtin_BYTES   Builtin = 13
	// Additional Encore Types
	Builtin_TIME    Builtin = 14
	Builtin_UUID    Builtin = 15
	Builtin_JSON    Builtin = 16
	Builtin_USER_ID Builtin = 17
	Builtin_INT     Builtin = 18
	Builtin_UINT    Builtin = 19
	Builtin_DECIMAL Builtin = 20
)

// Enum value maps for Builtin.
var (
	Builtin_name = map[int32]string{
		0:  "ANY",
		1:  "BOOL",
		2:  "INT8",
		3:  "INT16",
		4:  "INT32",
		5:  "INT64",
		6:  "UINT8",
		7:  "UINT16",
		8:  "UINT32",
		9:  "UINT64",
		10: "FLOAT32",
		11: "FLOAT64",
		12: "STRING",
		13: "BYTES",
		14: "TIME",
		15: "UUID",
		16: "JSON",
		17: "USER_ID",
		18: "INT",
		19: "UINT",
		20: "DECIMAL",
	}
	Builtin_value = map[string]int32{
		"ANY":     0,
		"BOOL":    1,
		"INT8":    2,
		"INT16":   3,
		"INT32":   4,
		"INT64":   5,
		"UINT8":   6,
		"UINT16":  7,
		"UINT32":  8,
		"UINT64":  9,
		"FLOAT32": 10,
		"FLOAT64": 11,
		"STRING":  12,
		"BYTES":   13,
		"TIME":    14,
		"UUID":    15,
		"JSON":    16,
		"USER_ID": 17,
		"INT":     18,
		"UINT":    19,
		"DECIMAL": 20,
	}
)

func (x Builtin) Enum() *Builtin {
	p := new(Builtin)
	*p = x
	return p
}

func (x Builtin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Builtin) Descriptor() protoreflect.EnumDescriptor {
	return file_encore_parser_schema_v1_schema_proto_enumTypes[0].Descriptor()
}

func (Builtin) Type() protoreflect.EnumType {
	return &file_encore_parser_schema_v1_schema_proto_enumTypes[0]
}

func (x Builtin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Builtin.Descriptor instead.
func (Builtin) EnumDescriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

type ValidationRule_Is int32

const (
	ValidationRule_UNKNOWN ValidationRule_Is = 0
	ValidationRule_EMAIL   ValidationRule_Is = 1
	ValidationRule_URL     ValidationRule_Is = 2
)

// Enum value maps for ValidationRule_Is.
var (
	ValidationRule_Is_name = map[int32]string{
		0: "UNKNOWN",
		1: "EMAIL",
		2: "URL",
	}
	ValidationRule_Is_value = map[string]int32{
		"UNKNOWN": 0,
		"EMAIL":   1,
		"URL":     2,
	}
)

func (x ValidationRule_Is) Enum() *ValidationRule_Is {
	p := new(ValidationRule_Is)
	*p = x
	return p
}

func (x ValidationRule_Is) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationRule_Is) Descriptor() protoreflect.EnumDescriptor {
	return file_encore_parser_schema_v1_schema_proto_enumTypes[1].Descriptor()
}

func (ValidationRule_Is) Type() protoreflect.EnumType {
	return &file_encore_parser_schema_v1_schema_proto_enumTypes[1]
}

func (x ValidationRule_Is) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationRule_Is.Descriptor instead.
func (ValidationRule_Is) EnumDescriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{1, 0}
}

// Type represents the base of our schema on which everything else is built on-top of. It has to be one, and only one,
// thing from our list of meta types.
//
// A type may be concrete or abstract, however to determine if a type is abstract you need to recursive through the
// structures looking for any uses of the TypeParameterPtr type
type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Typ:
	//
	//	*Type_Named
	//	*Type_Struct
	//	*Type_Map
	//	*Type_List
	//	*Type_Builtin
	//	*Type_Pointer
	//	*Type_Union
	//	*Type_Literal
	//	*Type_Option
	//	*Type_TypeParameter
	//	*Type_Config
	Typ           isType_Typ      `protobuf_oneof:"typ"`
	Validation    *ValidationExpr `protobuf:"bytes,15,opt,name=validation,proto3,oneof" json:"validation,omitempty"` // The validation expression for this type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetTyp() isType_Typ {
	if x != nil {
		return x.Typ
	}
	return nil
}

func (x *Type) GetNamed() *Named {
	if x != nil {
		if x, ok := x.Typ.(*Type_Named); ok {
			return x.Named
		}
	}
	return nil
}

func (x *Type) GetStruct() *Struct {
	if x != nil {
		if x, ok := x.Typ.(*Type_Struct); ok {
			return x.Struct
		}
	}
	return nil
}

func (x *Type) GetMap() *Map {
	if x != nil {
		if x, ok := x.Typ.(*Type_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *Type) GetList() *List {
	if x != nil {
		if x, ok := x.Typ.(*Type_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Type) GetBuiltin() Builtin {
	if x != nil {
		if x, ok := x.Typ.(*Type_Builtin); ok {
			return x.Builtin
		}
	}
	return Builtin_ANY
}

func (x *Type) GetPointer() *Pointer {
	if x != nil {
		if x, ok := x.Typ.(*Type_Pointer); ok {
			return x.Pointer
		}
	}
	return nil
}

func (x *Type) GetUnion() *Union {
	if x != nil {
		if x, ok := x.Typ.(*Type_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *Type) GetLiteral() *Literal {
	if x != nil {
		if x, ok := x.Typ.(*Type_Literal); ok {
			return x.Literal
		}
	}
	return nil
}

func (x *Type) GetOption() *Option {
	if x != nil {
		if x, ok := x.Typ.(*Type_Option); ok {
			return x.Option
		}
	}
	return nil
}

func (x *Type) GetTypeParameter() *TypeParameterRef {
	if x != nil {
		if x, ok := x.Typ.(*Type_TypeParameter); ok {
			return x.TypeParameter
		}
	}
	return nil
}

func (x *Type) GetConfig() *ConfigValue {
	if x != nil {
		if x, ok := x.Typ.(*Type_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *Type) GetValidation() *ValidationExpr {
	if x != nil {
		return x.Validation
	}
	return nil
}

type isType_Typ interface {
	isType_Typ()
}

type Type_Named struct {
	// Concrete / non-parameterized Types
	Named *Named `protobuf:"bytes,1,opt,name=named,proto3,oneof"` // A "named" type (https://tip.golang.org/ref/spec#Types)
}

type Type_Struct struct {
	Struct *Struct `protobuf:"bytes,2,opt,name=struct,proto3,oneof"` // The type is a struct definition
}

type Type_Map struct {
	Map *Map `protobuf:"bytes,3,opt,name=map,proto3,oneof"` // The type is a map
}

type Type_List struct {
	List *List `protobuf:"bytes,4,opt,name=list,proto3,oneof"` // The type is a slice
}

type Type_Builtin struct {
	Builtin Builtin `protobuf:"varint,5,opt,name=builtin,proto3,enum=encore.parser.schema.v1.Builtin,oneof"` // The type is one of the base built in types within Go
}

type Type_Pointer struct {
	Pointer *Pointer `protobuf:"bytes,8,opt,name=pointer,proto3,oneof"` // The type is a pointer
}

type Type_Union struct {
	Union *Union `protobuf:"bytes,9,opt,name=union,proto3,oneof"` // The type is a union
}

type Type_Literal struct {
	Literal *Literal `protobuf:"bytes,10,opt,name=literal,proto3,oneof"` // The type is a literal
}

type Type_Option struct {
	Option *Option `protobuf:"bytes,11,opt,name=option,proto3,oneof"` // The type is an option type
}

type Type_TypeParameter struct {
	// Abstract Types
	TypeParameter *TypeParameterRef `protobuf:"bytes,6,opt,name=type_parameter,json=typeParameter,proto3,oneof"` // This is placeholder for a unknown type within the declaration block
}

type Type_Config struct {
	// Encore Special Types
	Config *ConfigValue `protobuf:"bytes,7,opt,name=config,proto3,oneof"` // This value is a config value
}

func (*Type_Named) isType_Typ() {}

func (*Type_Struct) isType_Typ() {}

func (*Type_Map) isType_Typ() {}

func (*Type_List) isType_Typ() {}

func (*Type_Builtin) isType_Typ() {}

func (*Type_Pointer) isType_Typ() {}

func (*Type_Union) isType_Typ() {}

func (*Type_Literal) isType_Typ() {}

func (*Type_Option) isType_Typ() {}

func (*Type_TypeParameter) isType_Typ() {}

func (*Type_Config) isType_Typ() {}

type ValidationRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Rule:
	//
	//	*ValidationRule_MinLen
	//	*ValidationRule_MaxLen
	//	*ValidationRule_MinVal
	//	*ValidationRule_MaxVal
	//	*ValidationRule_StartsWith
	//	*ValidationRule_EndsWith
	//	*ValidationRule_MatchesRegexp
	//	*ValidationRule_Is_
	Rule          isValidationRule_Rule `protobuf_oneof:"rule"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRule) Reset() {
	*x = ValidationRule{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRule) ProtoMessage() {}

func (x *ValidationRule) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRule.ProtoReflect.Descriptor instead.
func (*ValidationRule) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationRule) GetRule() isValidationRule_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *ValidationRule) GetMinLen() uint64 {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_MinLen); ok {
			return x.MinLen
		}
	}
	return 0
}

func (x *ValidationRule) GetMaxLen() uint64 {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_MaxLen); ok {
			return x.MaxLen
		}
	}
	return 0
}

func (x *ValidationRule) GetMinVal() float64 {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_MinVal); ok {
			return x.MinVal
		}
	}
	return 0
}

func (x *ValidationRule) GetMaxVal() float64 {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_MaxVal); ok {
			return x.MaxVal
		}
	}
	return 0
}

func (x *ValidationRule) GetStartsWith() string {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_StartsWith); ok {
			return x.StartsWith
		}
	}
	return ""
}

func (x *ValidationRule) GetEndsWith() string {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_EndsWith); ok {
			return x.EndsWith
		}
	}
	return ""
}

func (x *ValidationRule) GetMatchesRegexp() string {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_MatchesRegexp); ok {
			return x.MatchesRegexp
		}
	}
	return ""
}

func (x *ValidationRule) GetIs() ValidationRule_Is {
	if x != nil {
		if x, ok := x.Rule.(*ValidationRule_Is_); ok {
			return x.Is
		}
	}
	return ValidationRule_UNKNOWN
}

type isValidationRule_Rule interface {
	isValidationRule_Rule()
}

type ValidationRule_MinLen struct {
	MinLen uint64 `protobuf:"varint,1,opt,name=min_len,json=minLen,proto3,oneof"`
}

type ValidationRule_MaxLen struct {
	MaxLen uint64 `protobuf:"varint,2,opt,name=max_len,json=maxLen,proto3,oneof"`
}

type ValidationRule_MinVal struct {
	MinVal float64 `protobuf:"fixed64,3,opt,name=min_val,json=minVal,proto3,oneof"`
}

type ValidationRule_MaxVal struct {
	MaxVal float64 `protobuf:"fixed64,4,opt,name=max_val,json=maxVal,proto3,oneof"`
}

type ValidationRule_StartsWith struct {
	StartsWith string `protobuf:"bytes,5,opt,name=starts_with,json=startsWith,proto3,oneof"`
}

type ValidationRule_EndsWith struct {
	EndsWith string `protobuf:"bytes,6,opt,name=ends_with,json=endsWith,proto3,oneof"`
}

type ValidationRule_MatchesRegexp struct {
	MatchesRegexp string `protobuf:"bytes,7,opt,name=matches_regexp,json=matchesRegexp,proto3,oneof"`
}

type ValidationRule_Is_ struct {
	Is ValidationRule_Is `protobuf:"varint,8,opt,name=is,proto3,enum=encore.parser.schema.v1.ValidationRule_Is,oneof"`
}

func (*ValidationRule_MinLen) isValidationRule_Rule() {}

func (*ValidationRule_MaxLen) isValidationRule_Rule() {}

func (*ValidationRule_MinVal) isValidationRule_Rule() {}

func (*ValidationRule_MaxVal) isValidationRule_Rule() {}

func (*ValidationRule_StartsWith) isValidationRule_Rule() {}

func (*ValidationRule_EndsWith) isValidationRule_Rule() {}

func (*ValidationRule_MatchesRegexp) isValidationRule_Rule() {}

func (*ValidationRule_Is_) isValidationRule_Rule() {}

type ValidationExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*ValidationExpr_Rule
	//	*ValidationExpr_And_
	//	*ValidationExpr_Or_
	Expr          isValidationExpr_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationExpr) Reset() {
	*x = ValidationExpr{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationExpr) ProtoMessage() {}

func (x *ValidationExpr) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationExpr.ProtoReflect.Descriptor instead.
func (*ValidationExpr) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationExpr) GetExpr() isValidationExpr_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *ValidationExpr) GetRule() *ValidationRule {
	if x != nil {
		if x, ok := x.Expr.(*ValidationExpr_Rule); ok {
			return x.Rule
		}
	}
	return nil
}

func (x *ValidationExpr) GetAnd() *ValidationExpr_And {
	if x != nil {
		if x, ok := x.Expr.(*ValidationExpr_And_); ok {
			return x.And
		}
	}
	return nil
}

func (x *ValidationExpr) GetOr() *ValidationExpr_Or {
	if x != nil {
		if x, ok := x.Expr.(*ValidationExpr_Or_); ok {
			return x.Or
		}
	}
	return nil
}

type isValidationExpr_Expr interface {
	isValidationExpr_Expr()
}

type ValidationExpr_Rule struct {
	Rule *ValidationRule `protobuf:"bytes,1,opt,name=rule,proto3,oneof"`
}

type ValidationExpr_And_ struct {
	And *ValidationExpr_And `protobuf:"bytes,2,opt,name=and,proto3,oneof"`
}

type ValidationExpr_Or_ struct {
	Or *ValidationExpr_Or `protobuf:"bytes,3,opt,name=or,proto3,oneof"`
}

func (*ValidationExpr_Rule) isValidationExpr_Expr() {}

func (*ValidationExpr_And_) isValidationExpr_Expr() {}

func (*ValidationExpr_Or_) isValidationExpr_Expr() {}

// TypeParameterRef is a reference to a `TypeParameter` within a declaration block
type TypeParameterRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclId        uint32                 `protobuf:"varint,1,opt,name=decl_id,json=declId,proto3" json:"decl_id,omitempty"`       // The ID of the declaration block
	ParamIdx      uint32                 `protobuf:"varint,2,opt,name=param_idx,json=paramIdx,proto3" json:"param_idx,omitempty"` // The index of the type parameter within the declaration block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeParameterRef) Reset() {
	*x = TypeParameterRef{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeParameterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeParameterRef) ProtoMessage() {}

func (x *TypeParameterRef) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeParameterRef.ProtoReflect.Descriptor instead.
func (*TypeParameterRef) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *TypeParameterRef) GetDeclId() uint32 {
	if x != nil {
		return x.DeclId
	}
	return 0
}

func (x *TypeParameterRef) GetParamIdx() uint32 {
	if x != nil {
		return x.ParamIdx
	}
	return 0
}

// Decl represents the declaration of a type within the Go code which is either concrete or _parameterized_. The type is
// concrete when there are zero type parameters assigned.
//
// For example the Go Code:
// ```go
// // Set[A] represents our set type
// type Set[A any] = map[A]struct{}
// ```
//
// Would become:
// ```go
//
//	_ = &Decl{
//	    id: 1,
//	    name: "Set",
//	    type: &Type{
//	        typ_map: &Map{
//	            key: &Type { typ_type_parameter: ... reference to "A" type parameter below ... },
//	            value: &Type { typ_struct: ... empty struct type ... },
//	        },
//	    },
//	    typeParameters: []*TypeParameter{ { name: "A" } },
//	    doc: "Set[A] represents our set type",
//	    loc: &Loc { ... },
//	}
//
// ```
type Decl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // A internal ID which we can refer to this declaration by
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // The name of the type as assigned in the code
	Type          *Type                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                               // The underlying type of this declaration
	TypeParams    []*TypeParameter       `protobuf:"bytes,6,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"` // Any type parameters on this declaration (note; instantiated types used within this declaration would not be captured here)
	Doc           string                 `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`                                 // The comment block on the type
	Loc           *Loc                   `protobuf:"bytes,5,opt,name=loc,proto3" json:"loc,omitempty"`                                 // The location of the declaration within the project
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decl) Reset() {
	*x = Decl{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decl) ProtoMessage() {}

func (x *Decl) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decl.ProtoReflect.Descriptor instead.
func (*Decl) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Decl) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Decl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Decl) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Decl) GetTypeParams() []*TypeParameter {
	if x != nil {
		return x.TypeParams
	}
	return nil
}

func (x *Decl) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Decl) GetLoc() *Loc {
	if x != nil {
		return x.Loc
	}
	return nil
}

// TypeParameter acts as a place holder for an (as of yet) unknown type in the declaration; the type parameter is
// replaced with a type argument upon instantiation of the parameterized function or type.
type TypeParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // The identifier given to the type parameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeParameter) Reset() {
	*x = TypeParameter{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeParameter) ProtoMessage() {}

func (x *TypeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeParameter.ProtoReflect.Descriptor instead.
func (*TypeParameter) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{5}
}

func (x *TypeParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Loc is the location of a declaration within the code base
type Loc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkgPath       string                 `protobuf:"bytes,1,opt,name=pkg_path,json=pkgPath,proto3" json:"pkg_path,omitempty"`                   // The package path within the repo (i.e. `users/signup`)
	PkgName       string                 `protobuf:"bytes,2,opt,name=pkg_name,json=pkgName,proto3" json:"pkg_name,omitempty"`                   // The package name (i.e. `signup`)
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                                // The file name (i.e. `signup.go`)
	StartPos      int32                  `protobuf:"varint,4,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`               // The starting index within the file for this node
	EndPos        int32                  `protobuf:"varint,5,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`                     // The ending index within the file for this node
	SrcLineStart  int32                  `protobuf:"varint,6,opt,name=src_line_start,json=srcLineStart,proto3" json:"src_line_start,omitempty"` // The starting line within the file for this node
	SrcLineEnd    int32                  `protobuf:"varint,7,opt,name=src_line_end,json=srcLineEnd,proto3" json:"src_line_end,omitempty"`       // The ending line within the file for this node
	SrcColStart   int32                  `protobuf:"varint,8,opt,name=src_col_start,json=srcColStart,proto3" json:"src_col_start,omitempty"`    // The starting column on the starting line for this node
	SrcColEnd     int32                  `protobuf:"varint,9,opt,name=src_col_end,json=srcColEnd,proto3" json:"src_col_end,omitempty"`          // The ending column on the ending line for this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loc) Reset() {
	*x = Loc{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loc) ProtoMessage() {}

func (x *Loc) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loc.ProtoReflect.Descriptor instead.
func (*Loc) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{6}
}

func (x *Loc) GetPkgPath() string {
	if x != nil {
		return x.PkgPath
	}
	return ""
}

func (x *Loc) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *Loc) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Loc) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Loc) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Loc) GetSrcLineStart() int32 {
	if x != nil {
		return x.SrcLineStart
	}
	return 0
}

func (x *Loc) GetSrcLineEnd() int32 {
	if x != nil {
		return x.SrcLineEnd
	}
	return 0
}

func (x *Loc) GetSrcColStart() int32 {
	if x != nil {
		return x.SrcColStart
	}
	return 0
}

func (x *Loc) GetSrcColEnd() int32 {
	if x != nil {
		return x.SrcColEnd
	}
	return 0
}

// Named references declaration block by name
type Named struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // The `Decl.id` this name refers to
	TypeArguments []*Type                `protobuf:"bytes,2,rep,name=type_arguments,json=typeArguments,proto3" json:"type_arguments,omitempty"` // The type arguments used to instantiate this parameterised declaration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Named) Reset() {
	*x = Named{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Named) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Named) ProtoMessage() {}

func (x *Named) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Named.ProtoReflect.Descriptor instead.
func (*Named) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{7}
}

func (x *Named) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Named) GetTypeArguments() []*Type {
	if x != nil {
		return x.TypeArguments
	}
	return nil
}

// Struct contains a list of fields which make up the struct
type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{8}
}

func (x *Struct) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field represents a field within a struct
type Field struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Typ             *Type                  `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`                                                  // The type of the field
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                // The name of the field
	Doc             string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`                                                  // The comment for the field
	JsonName        string                 `protobuf:"bytes,4,opt,name=json_name,json=jsonName,proto3" json:"json_name,omitempty"`                        // The optional json name if it's different from the field name. (The value "-" indicates to omit the field.)
	Optional        bool                   `protobuf:"varint,5,opt,name=optional,proto3" json:"optional,omitempty"`                                       // Whether the field is optional.
	QueryStringName string                 `protobuf:"bytes,6,opt,name=query_string_name,json=queryStringName,proto3" json:"query_string_name,omitempty"` // The query string name to use in GET/HEAD/DELETE requests. (The value "-" indicates to omit the field.)
	RawTag          string                 `protobuf:"bytes,7,opt,name=raw_tag,json=rawTag,proto3" json:"raw_tag,omitempty"`                              // The original Go struct tag; should not be parsed individually
	Tags            []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                                // Parsed go struct tags. Used for marshalling hints
	Wire            *WireSpec              `protobuf:"bytes,9,opt,name=wire,proto3,oneof" json:"wire,omitempty"`                                          // The explicitly set wire location of the field.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{9}
}

func (x *Field) GetTyp() *Type {
	if x != nil {
		return x.Typ
	}
	return nil
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Field) GetJsonName() string {
	if x != nil {
		return x.JsonName
	}
	return ""
}

func (x *Field) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *Field) GetQueryStringName() string {
	if x != nil {
		return x.QueryStringName
	}
	return ""
}

func (x *Field) GetRawTag() string {
	if x != nil {
		return x.RawTag
	}
	return ""
}

func (x *Field) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Field) GetWire() *WireSpec {
	if x != nil {
		return x.Wire
	}
	return nil
}

// WireLocation provides information about how a field should be encoded on the wire.
type WireSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*WireSpec_Header_
	//	*WireSpec_Query_
	//	*WireSpec_Cookie_
	//	*WireSpec_HttpStatus_
	Location      isWireSpec_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSpec) Reset() {
	*x = WireSpec{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSpec) ProtoMessage() {}

func (x *WireSpec) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSpec.ProtoReflect.Descriptor instead.
func (*WireSpec) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{10}
}

func (x *WireSpec) GetLocation() isWireSpec_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *WireSpec) GetHeader() *WireSpec_Header {
	if x != nil {
		if x, ok := x.Location.(*WireSpec_Header_); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WireSpec) GetQuery() *WireSpec_Query {
	if x != nil {
		if x, ok := x.Location.(*WireSpec_Query_); ok {
			return x.Query
		}
	}
	return nil
}

func (x *WireSpec) GetCookie() *WireSpec_Cookie {
	if x != nil {
		if x, ok := x.Location.(*WireSpec_Cookie_); ok {
			return x.Cookie
		}
	}
	return nil
}

func (x *WireSpec) GetHttpStatus() *WireSpec_HttpStatus {
	if x != nil {
		if x, ok := x.Location.(*WireSpec_HttpStatus_); ok {
			return x.HttpStatus
		}
	}
	return nil
}

type isWireSpec_Location interface {
	isWireSpec_Location()
}

type WireSpec_Header_ struct {
	Header *WireSpec_Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type WireSpec_Query_ struct {
	Query *WireSpec_Query `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

type WireSpec_Cookie_ struct {
	Cookie *WireSpec_Cookie `protobuf:"bytes,3,opt,name=cookie,proto3,oneof"`
}

type WireSpec_HttpStatus_ struct {
	HttpStatus *WireSpec_HttpStatus `protobuf:"bytes,4,opt,name=http_status,json=httpStatus,proto3,oneof"`
}

func (*WireSpec_Header_) isWireSpec_Location() {}

func (*WireSpec_Query_) isWireSpec_Location() {}

func (*WireSpec_Cookie_) isWireSpec_Location() {}

func (*WireSpec_HttpStatus_) isWireSpec_Location() {}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // The tag key (e.g. json, query, header ...)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // The tag name (e.g. first_name, firstName, ...)
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"` // Key Options (e.g. omitempty, optional ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{11}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Map represents a map Type
type Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Type                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // The type of the key for this map
	Value         *Type                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The type of the value of this map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{12}
}

func (x *Map) GetKey() *Type {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Map) GetValue() *Type {
	if x != nil {
		return x.Value
	}
	return nil
}

// List represents a list type (array or slice)
type List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elem          *Type                  `protobuf:"bytes,1,opt,name=elem,proto3" json:"elem,omitempty"` // The type of the elements in the list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{13}
}

func (x *List) GetElem() *Type {
	if x != nil {
		return x.Elem
	}
	return nil
}

// Pointer represents a pointer to a base type
type Pointer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Type                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // The type of the pointer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pointer) Reset() {
	*x = Pointer{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pointer) ProtoMessage() {}

func (x *Pointer) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pointer.ProtoReflect.Descriptor instead.
func (*Pointer) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{14}
}

func (x *Pointer) GetBase() *Type {
	if x != nil {
		return x.Base
	}
	return nil
}

// Option represents an option type.
type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Type                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // The value it may contain.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{15}
}

func (x *Option) GetValue() *Type {
	if x != nil {
		return x.Value
	}
	return nil
}

// Union represents a union type.
type Union struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*Type                `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"` // The types that make up the union
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Union) Reset() {
	*x = Union{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Union) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Union) ProtoMessage() {}

func (x *Union) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Union.ProtoReflect.Descriptor instead.
func (*Union) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{16}
}

func (x *Union) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

// Literal represents a literal value.
type Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Literal_Str
	//	*Literal_Boolean
	//	*Literal_Int
	//	*Literal_Float
	//	*Literal_Null
	Value         isLiteral_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{17}
}

func (x *Literal) GetValue() isLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Literal) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Literal) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Literal) GetInt() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Literal) GetFloat() float64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *Literal) GetNull() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_Null); ok {
			return x.Null
		}
	}
	return false
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Literal_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type Literal_Int struct {
	Int int64 `protobuf:"varint,3,opt,name=int,proto3,oneof"`
}

type Literal_Float struct {
	Float float64 `protobuf:"fixed64,4,opt,name=float,proto3,oneof"`
}

type Literal_Null struct {
	Null bool `protobuf:"varint,5,opt,name=null,proto3,oneof"`
}

func (*Literal_Str) isLiteral_Value() {}

func (*Literal_Boolean) isLiteral_Value() {}

func (*Literal_Int) isLiteral_Value() {}

func (*Literal_Float) isLiteral_Value() {}

func (*Literal_Null) isLiteral_Value() {}

// ConfigValue represents a config value wrapper.
type ConfigValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elem          *Type                  `protobuf:"bytes,1,opt,name=elem,proto3" json:"elem,omitempty"`                  // The type of the config value
	IsValuesList  bool                   `protobuf:"varint,2,opt,name=IsValuesList,proto3" json:"IsValuesList,omitempty"` // Does this config value represent the type to `config.Values[T]`. If false it represents `config.Value[T]`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigValue) GetElem() *Type {
	if x != nil {
		return x.Elem
	}
	return nil
}

func (x *ConfigValue) GetIsValuesList() bool {
	if x != nil {
		return x.IsValuesList
	}
	return false
}

type ValidationExpr_And struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exprs         []*ValidationExpr      `protobuf:"bytes,1,rep,name=exprs,proto3" json:"exprs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationExpr_And) Reset() {
	*x = ValidationExpr_And{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationExpr_And) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationExpr_And) ProtoMessage() {}

func (x *ValidationExpr_And) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationExpr_And.ProtoReflect.Descriptor instead.
func (*ValidationExpr_And) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ValidationExpr_And) GetExprs() []*ValidationExpr {
	if x != nil {
		return x.Exprs
	}
	return nil
}

type ValidationExpr_Or struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exprs         []*ValidationExpr      `protobuf:"bytes,1,rep,name=exprs,proto3" json:"exprs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationExpr_Or) Reset() {
	*x = ValidationExpr_Or{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationExpr_Or) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationExpr_Or) ProtoMessage() {}

func (x *ValidationExpr_Or) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationExpr_Or.ProtoReflect.Descriptor instead.
func (*ValidationExpr_Or) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ValidationExpr_Or) GetExprs() []*ValidationExpr {
	if x != nil {
		return x.Exprs
	}
	return nil
}

type WireSpec_Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The explicitly specified header name.
	// If empty, the name of the field is used.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSpec_Header) Reset() {
	*x = WireSpec_Header{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSpec_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSpec_Header) ProtoMessage() {}

func (x *WireSpec_Header) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSpec_Header.ProtoReflect.Descriptor instead.
func (*WireSpec_Header) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{10, 0}
}

func (x *WireSpec_Header) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type WireSpec_Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The explicitly specified query string name.
	// If empty, the name of the field is used.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSpec_Query) Reset() {
	*x = WireSpec_Query{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSpec_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSpec_Query) ProtoMessage() {}

func (x *WireSpec_Query) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSpec_Query.ProtoReflect.Descriptor instead.
func (*WireSpec_Query) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{10, 1}
}

func (x *WireSpec_Query) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type WireSpec_Cookie struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The explicitly specified cookie string name.
	// If empty, the name of the field is used.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSpec_Cookie) Reset() {
	*x = WireSpec_Cookie{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSpec_Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSpec_Cookie) ProtoMessage() {}

func (x *WireSpec_Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSpec_Cookie.ProtoReflect.Descriptor instead.
func (*WireSpec_Cookie) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{10, 2}
}

func (x *WireSpec_Cookie) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type WireSpec_HttpStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSpec_HttpStatus) Reset() {
	*x = WireSpec_HttpStatus{}
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSpec_HttpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSpec_HttpStatus) ProtoMessage() {}

func (x *WireSpec_HttpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_encore_parser_schema_v1_schema_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSpec_HttpStatus.ProtoReflect.Descriptor instead.
func (*WireSpec_HttpStatus) Descriptor() ([]byte, []int) {
	return file_encore_parser_schema_v1_schema_proto_rawDescGZIP(), []int{10, 3}
}

var File_encore_parser_schema_v1_schema_proto protoreflect.FileDescriptor

const file_encore_parser_schema_v1_schema_proto_rawDesc = "" +
	"\n" +
	"$encore/parser/schema/v1/schema.proto\x12\x17encore.parser.schema.v1\"\x85\x06\n" +
	"\x04Type\x126\n" +
	"\x05named\x18\x01 \x01(\v2\x1e.encore.parser.schema.v1.NamedH\x00R\x05named\x129\n" +
	"\x06struct\x18\x02 \x01(\v2\x1f.encore.parser.schema.v1.StructH\x00R\x06struct\x120\n" +
	"\x03map\x18\x03 \x01(\v2\x1c.encore.parser.schema.v1.MapH\x00R\x03map\x123\n" +
	"\x04list\x18\x04 \x01(\v2\x1d.encore.parser.schema.v1.ListH\x00R\x04list\x12<\n" +
	"\abuiltin\x18\x05 \x01(\x0e2 .encore.parser.schema.v1.BuiltinH\x00R\abuiltin\x12<\n" +
	"\apointer\x18\b \x01(\v2 .encore.parser.schema.v1.PointerH\x00R\apointer\x126\n" +
	"\x05union\x18\t \x01(\v2\x1e.encore.parser.schema.v1.UnionH\x00R\x05union\x12<\n" +
	"\aliteral\x18\n" +
	" \x01(\v2 .encore.parser.schema.v1.LiteralH\x00R\aliteral\x129\n" +
	"\x06option\x18\v \x01(\v2\x1f.encore.parser.schema.v1.OptionH\x00R\x06option\x12R\n" +
	"\x0etype_parameter\x18\x06 \x01(\v2).encore.parser.schema.v1.TypeParameterRefH\x00R\rtypeParameter\x12>\n" +
	"\x06config\x18\a \x01(\v2$.encore.parser.schema.v1.ConfigValueH\x00R\x06config\x12L\n" +
	"\n" +
	"validation\x18\x0f \x01(\v2'.encore.parser.schema.v1.ValidationExprH\x01R\n" +
	"validation\x88\x01\x01B\x05\n" +
	"\x03typB\r\n" +
	"\v_validation\"\xd4\x02\n" +
	"\x0eValidationRule\x12\x19\n" +
	"\amin_len\x18\x01 \x01(\x04H\x00R\x06minLen\x12\x19\n" +
	"\amax_len\x18\x02 \x01(\x04H\x00R\x06maxLen\x12\x19\n" +
	"\amin_val\x18\x03 \x01(\x01H\x00R\x06minVal\x12\x19\n" +
	"\amax_val\x18\x04 \x01(\x01H\x00R\x06maxVal\x12!\n" +
	"\vstarts_with\x18\x05 \x01(\tH\x00R\n" +
	"startsWith\x12\x1d\n" +
	"\tends_with\x18\x06 \x01(\tH\x00R\bendsWith\x12'\n" +
	"\x0ematches_regexp\x18\a \x01(\tH\x00R\rmatchesRegexp\x12<\n" +
	"\x02is\x18\b \x01(\x0e2*.encore.parser.schema.v1.ValidationRule.IsH\x00R\x02is\"%\n" +
	"\x02Is\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x01\x12\a\n" +
	"\x03URL\x10\x02B\x06\n" +
	"\x04rule\"\xe1\x02\n" +
	"\x0eValidationExpr\x12=\n" +
	"\x04rule\x18\x01 \x01(\v2'.encore.parser.schema.v1.ValidationRuleH\x00R\x04rule\x12?\n" +
	"\x03and\x18\x02 \x01(\v2+.encore.parser.schema.v1.ValidationExpr.AndH\x00R\x03and\x12<\n" +
	"\x02or\x18\x03 \x01(\v2*.encore.parser.schema.v1.ValidationExpr.OrH\x00R\x02or\x1aD\n" +
	"\x03And\x12=\n" +
	"\x05exprs\x18\x01 \x03(\v2'.encore.parser.schema.v1.ValidationExprR\x05exprs\x1aC\n" +
	"\x02Or\x12=\n" +
	"\x05exprs\x18\x01 \x03(\v2'.encore.parser.schema.v1.ValidationExprR\x05exprsB\x06\n" +
	"\x04expr\"H\n" +
	"\x10TypeParameterRef\x12\x17\n" +
	"\adecl_id\x18\x01 \x01(\rR\x06declId\x12\x1b\n" +
	"\tparam_idx\x18\x02 \x01(\rR\bparamIdx\"\xe8\x01\n" +
	"\x04Decl\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x03 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x04type\x12G\n" +
	"\vtype_params\x18\x06 \x03(\v2&.encore.parser.schema.v1.TypeParameterR\n" +
	"typeParams\x12\x10\n" +
	"\x03doc\x18\x04 \x01(\tR\x03doc\x12.\n" +
	"\x03loc\x18\x05 \x01(\v2\x1c.encore.parser.schema.v1.LocR\x03loc\"#\n" +
	"\rTypeParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x99\x02\n" +
	"\x03Loc\x12\x19\n" +
	"\bpkg_path\x18\x01 \x01(\tR\apkgPath\x12\x19\n" +
	"\bpkg_name\x18\x02 \x01(\tR\apkgName\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tstart_pos\x18\x04 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x05 \x01(\x05R\x06endPos\x12$\n" +
	"\x0esrc_line_start\x18\x06 \x01(\x05R\fsrcLineStart\x12 \n" +
	"\fsrc_line_end\x18\a \x01(\x05R\n" +
	"srcLineEnd\x12\"\n" +
	"\rsrc_col_start\x18\b \x01(\x05R\vsrcColStart\x12\x1e\n" +
	"\vsrc_col_end\x18\t \x01(\x05R\tsrcColEnd\"]\n" +
	"\x05Named\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12D\n" +
	"\x0etype_arguments\x18\x02 \x03(\v2\x1d.encore.parser.schema.v1.TypeR\rtypeArguments\"@\n" +
	"\x06Struct\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.encore.parser.schema.v1.FieldR\x06fields\"\xd3\x02\n" +
	"\x05Field\x12/\n" +
	"\x03typ\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x03typ\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12\x1b\n" +
	"\tjson_name\x18\x04 \x01(\tR\bjsonName\x12\x1a\n" +
	"\boptional\x18\x05 \x01(\bR\boptional\x12*\n" +
	"\x11query_string_name\x18\x06 \x01(\tR\x0fqueryStringName\x12\x17\n" +
	"\araw_tag\x18\a \x01(\tR\x06rawTag\x120\n" +
	"\x04tags\x18\b \x03(\v2\x1c.encore.parser.schema.v1.TagR\x04tags\x12:\n" +
	"\x04wire\x18\t \x01(\v2!.encore.parser.schema.v1.WireSpecH\x00R\x04wire\x88\x01\x01B\a\n" +
	"\x05_wire\"\xc1\x03\n" +
	"\bWireSpec\x12B\n" +
	"\x06header\x18\x01 \x01(\v2(.encore.parser.schema.v1.WireSpec.HeaderH\x00R\x06header\x12?\n" +
	"\x05query\x18\x02 \x01(\v2'.encore.parser.schema.v1.WireSpec.QueryH\x00R\x05query\x12B\n" +
	"\x06cookie\x18\x03 \x01(\v2(.encore.parser.schema.v1.WireSpec.CookieH\x00R\x06cookie\x12O\n" +
	"\vhttp_status\x18\x04 \x01(\v2,.encore.parser.schema.v1.WireSpec.HttpStatusH\x00R\n" +
	"httpStatus\x1a*\n" +
	"\x06Header\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\x1a)\n" +
	"\x05Query\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\x1a*\n" +
	"\x06Cookie\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\x1a\f\n" +
	"\n" +
	"HttpStatusB\n" +
	"\n" +
	"\blocation\"E\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"k\n" +
	"\x03Map\x12/\n" +
	"\x03key\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x05value\"9\n" +
	"\x04List\x121\n" +
	"\x04elem\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x04elem\"<\n" +
	"\aPointer\x121\n" +
	"\x04base\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x04base\"=\n" +
	"\x06Option\x123\n" +
	"\x05value\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x05value\"<\n" +
	"\x05Union\x123\n" +
	"\x05types\x18\x01 \x03(\v2\x1d.encore.parser.schema.v1.TypeR\x05types\"\x84\x01\n" +
	"\aLiteral\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x12\n" +
	"\x03int\x18\x03 \x01(\x03H\x00R\x03int\x12\x16\n" +
	"\x05float\x18\x04 \x01(\x01H\x00R\x05float\x12\x14\n" +
	"\x04null\x18\x05 \x01(\bH\x00R\x04nullB\a\n" +
	"\x05value\"d\n" +
	"\vConfigValue\x121\n" +
	"\x04elem\x18\x01 \x01(\v2\x1d.encore.parser.schema.v1.TypeR\x04elem\x12\"\n" +
	"\fIsValuesList\x18\x02 \x01(\bR\fIsValuesList*\xf2\x01\n" +
	"\aBuiltin\x12\a\n" +
	"\x03ANY\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\b\n" +
	"\x04INT8\x10\x02\x12\t\n" +
	"\x05INT16\x10\x03\x12\t\n" +
	"\x05INT32\x10\x04\x12\t\n" +
	"\x05INT64\x10\x05\x12\t\n" +
	"\x05UINT8\x10\x06\x12\n" +
	"\n" +
	"\x06UINT16\x10\a\x12\n" +
	"\n" +
	"\x06UINT32\x10\b\x12\n" +
	"\n" +
	"\x06UINT64\x10\t\x12\v\n" +
	"\aFLOAT32\x10\n" +
	"\x12\v\n" +
	"\aFLOAT64\x10\v\x12\n" +
	"\n" +
	"\x06STRING\x10\f\x12\t\n" +
	"\x05BYTES\x10\r\x12\b\n" +
	"\x04TIME\x10\x0e\x12\b\n" +
	"\x04UUID\x10\x0f\x12\b\n" +
	"\x04JSON\x10\x10\x12\v\n" +
	"\aUSER_ID\x10\x11\x12\a\n" +
	"\x03INT\x10\x12\x12\b\n" +
	"\x04UINT\x10\x13\x12\v\n" +
	"\aDECIMAL\x10\x14B(Z&encr.dev/proto/encore/parser/schema/v1b\x06proto3"

var (
	file_encore_parser_schema_v1_schema_proto_rawDescOnce sync.Once
	file_encore_parser_schema_v1_schema_proto_rawDescData []byte
)

func file_encore_parser_schema_v1_schema_proto_rawDescGZIP() []byte {
	file_encore_parser_schema_v1_schema_proto_rawDescOnce.Do(func() {
		file_encore_parser_schema_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encore_parser_schema_v1_schema_proto_rawDesc), len(file_encore_parser_schema_v1_schema_proto_rawDesc)))
	})
	return file_encore_parser_schema_v1_schema_proto_rawDescData
}

var file_encore_parser_schema_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encore_parser_schema_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_encore_parser_schema_v1_schema_proto_goTypes = []any{
	(Builtin)(0),                // 0: encore.parser.schema.v1.Builtin
	(ValidationRule_Is)(0),      // 1: encore.parser.schema.v1.ValidationRule.Is
	(*Type)(nil),                // 2: encore.parser.schema.v1.Type
	(*ValidationRule)(nil),      // 3: encore.parser.schema.v1.ValidationRule
	(*ValidationExpr)(nil),      // 4: encore.parser.schema.v1.ValidationExpr
	(*TypeParameterRef)(nil),    // 5: encore.parser.schema.v1.TypeParameterRef
	(*Decl)(nil),                // 6: encore.parser.schema.v1.Decl
	(*TypeParameter)(nil),       // 7: encore.parser.schema.v1.TypeParameter
	(*Loc)(nil),                 // 8: encore.parser.schema.v1.Loc
	(*Named)(nil),               // 9: encore.parser.schema.v1.Named
	(*Struct)(nil),              // 10: encore.parser.schema.v1.Struct
	(*Field)(nil),               // 11: encore.parser.schema.v1.Field
	(*WireSpec)(nil),            // 12: encore.parser.schema.v1.WireSpec
	(*Tag)(nil),                 // 13: encore.parser.schema.v1.Tag
	(*Map)(nil),                 // 14: encore.parser.schema.v1.Map
	(*List)(nil),                // 15: encore.parser.schema.v1.List
	(*Pointer)(nil),             // 16: encore.parser.schema.v1.Pointer
	(*Option)(nil),              // 17: encore.parser.schema.v1.Option
	(*Union)(nil),               // 18: encore.parser.schema.v1.Union
	(*Literal)(nil),             // 19: encore.parser.schema.v1.Literal
	(*ConfigValue)(nil),         // 20: encore.parser.schema.v1.ConfigValue
	(*ValidationExpr_And)(nil),  // 21: encore.parser.schema.v1.ValidationExpr.And
	(*ValidationExpr_Or)(nil),   // 22: encore.parser.schema.v1.ValidationExpr.Or
	(*WireSpec_Header)(nil),     // 23: encore.parser.schema.v1.WireSpec.Header
	(*WireSpec_Query)(nil),      // 24: encore.parser.schema.v1.WireSpec.Query
	(*WireSpec_Cookie)(nil),     // 25: encore.parser.schema.v1.WireSpec.Cookie
	(*WireSpec_HttpStatus)(nil), // 26: encore.parser.schema.v1.WireSpec.HttpStatus
}
var file_encore_parser_schema_v1_schema_proto_depIdxs = []int32{
	9,  // 0: encore.parser.schema.v1.Type.named:type_name -> encore.parser.schema.v1.Named
	10, // 1: encore.parser.schema.v1.Type.struct:type_name -> encore.parser.schema.v1.Struct
	14, // 2: encore.parser.schema.v1.Type.map:type_name -> encore.parser.schema.v1.Map
	15, // 3: encore.parser.schema.v1.Type.list:type_name -> encore.parser.schema.v1.List
	0,  // 4: encore.parser.schema.v1.Type.builtin:type_name -> encore.parser.schema.v1.Builtin
	16, // 5: encore.parser.schema.v1.Type.pointer:type_name -> encore.parser.schema.v1.Pointer
	18, // 6: encore.parser.schema.v1.Type.union:type_name -> encore.parser.schema.v1.Union
	19, // 7: encore.parser.schema.v1.Type.literal:type_name -> encore.parser.schema.v1.Literal
	17, // 8: encore.parser.schema.v1.Type.option:type_name -> encore.parser.schema.v1.Option
	5,  // 9: encore.parser.schema.v1.Type.type_parameter:type_name -> encore.parser.schema.v1.TypeParameterRef
	20, // 10: encore.parser.schema.v1.Type.config:type_name -> encore.parser.schema.v1.ConfigValue
	4,  // 11: encore.parser.schema.v1.Type.validation:type_name -> encore.parser.schema.v1.ValidationExpr
	1,  // 12: encore.parser.schema.v1.ValidationRule.is:type_name -> encore.parser.schema.v1.ValidationRule.Is
	3,  // 13: encore.parser.schema.v1.ValidationExpr.rule:type_name -> encore.parser.schema.v1.ValidationRule
	21, // 14: encore.parser.schema.v1.ValidationExpr.and:type_name -> encore.parser.schema.v1.ValidationExpr.And
	22, // 15: encore.parser.schema.v1.ValidationExpr.or:type_name -> encore.parser.schema.v1.ValidationExpr.Or
	2,  // 16: encore.parser.schema.v1.Decl.type:type_name -> encore.parser.schema.v1.Type
	7,  // 17: encore.parser.schema.v1.Decl.type_params:type_name -> encore.parser.schema.v1.TypeParameter
	8,  // 18: encore.parser.schema.v1.Decl.loc:type_name -> encore.parser.schema.v1.Loc
	2,  // 19: encore.parser.schema.v1.Named.type_arguments:type_name -> encore.parser.schema.v1.Type
	11, // 20: encore.parser.schema.v1.Struct.fields:type_name -> encore.parser.schema.v1.Field
	2,  // 21: encore.parser.schema.v1.Field.typ:type_name -> encore.parser.schema.v1.Type
	13, // 22: encore.parser.schema.v1.Field.tags:type_name -> encore.parser.schema.v1.Tag
	12, // 23: encore.parser.schema.v1.Field.wire:type_name -> encore.parser.schema.v1.WireSpec
	23, // 24: encore.parser.schema.v1.WireSpec.header:type_name -> encore.parser.schema.v1.WireSpec.Header
	24, // 25: encore.parser.schema.v1.WireSpec.query:type_name -> encore.parser.schema.v1.WireSpec.Query
	25, // 26: encore.parser.schema.v1.WireSpec.cookie:type_name -> encore.parser.schema.v1.WireSpec.Cookie
	26, // 27: encore.parser.schema.v1.WireSpec.http_status:type_name -> encore.parser.schema.v1.WireSpec.HttpStatus
	2,  // 28: encore.parser.schema.v1.Map.key:type_name -> encore.parser.schema.v1.Type
	2,  // 29: encore.parser.schema.v1.Map.value:type_name -> encore.parser.schema.v1.Type
	2,  // 30: encore.parser.schema.v1.List.elem:type_name -> encore.parser.schema.v1.Type
	2,  // 31: encore.parser.schema.v1.Pointer.base:type_name -> encore.parser.schema.v1.Type
	2,  // 32: encore.parser.schema.v1.Option.value:type_name -> encore.parser.schema.v1.Type
	2,  // 33: encore.parser.schema.v1.Union.types:type_name -> encore.parser.schema.v1.Type
	2,  // 34: encore.parser.schema.v1.ConfigValue.elem:type_name -> encore.parser.schema.v1.Type
	4,  // 35: encore.parser.schema.v1.ValidationExpr.And.exprs:type_name -> encore.parser.schema.v1.ValidationExpr
	4,  // 36: encore.parser.schema.v1.ValidationExpr.Or.exprs:type_name -> encore.parser.schema.v1.ValidationExpr
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_encore_parser_schema_v1_schema_proto_init() }
func file_encore_parser_schema_v1_schema_proto_init() {
	if File_encore_parser_schema_v1_schema_proto != nil {
		return
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[0].OneofWrappers = []any{
		(*Type_Named)(nil),
		(*Type_Struct)(nil),
		(*Type_Map)(nil),
		(*Type_List)(nil),
		(*Type_Builtin)(nil),
		(*Type_Pointer)(nil),
		(*Type_Union)(nil),
		(*Type_Literal)(nil),
		(*Type_Option)(nil),
		(*Type_TypeParameter)(nil),
		(*Type_Config)(nil),
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[1].OneofWrappers = []any{
		(*ValidationRule_MinLen)(nil),
		(*ValidationRule_MaxLen)(nil),
		(*ValidationRule_MinVal)(nil),
		(*ValidationRule_MaxVal)(nil),
		(*ValidationRule_StartsWith)(nil),
		(*ValidationRule_EndsWith)(nil),
		(*ValidationRule_MatchesRegexp)(nil),
		(*ValidationRule_Is_)(nil),
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[2].OneofWrappers = []any{
		(*ValidationExpr_Rule)(nil),
		(*ValidationExpr_And_)(nil),
		(*ValidationExpr_Or_)(nil),
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[9].OneofWrappers = []any{}
	file_encore_parser_schema_v1_schema_proto_msgTypes[10].OneofWrappers = []any{
		(*WireSpec_Header_)(nil),
		(*WireSpec_Query_)(nil),
		(*WireSpec_Cookie_)(nil),
		(*WireSpec_HttpStatus_)(nil),
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[17].OneofWrappers = []any{
		(*Literal_Str)(nil),
		(*Literal_Boolean)(nil),
		(*Literal_Int)(nil),
		(*Literal_Float)(nil),
		(*Literal_Null)(nil),
	}
	file_encore_parser_schema_v1_schema_proto_msgTypes[21].OneofWrappers = []any{}
	file_encore_parser_schema_v1_schema_proto_msgTypes[22].OneofWrappers = []any{}
	file_encore_parser_schema_v1_schema_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encore_parser_schema_v1_schema_proto_rawDesc), len(file_encore_parser_schema_v1_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encore_parser_schema_v1_schema_proto_goTypes,
		DependencyIndexes: file_encore_parser_schema_v1_schema_proto_depIdxs,
		EnumInfos:         file_encore_parser_schema_v1_schema_proto_enumTypes,
		MessageInfos:      file_encore_parser_schema_v1_schema_proto_msgTypes,
	}.Build()
	File_encore_parser_schema_v1_schema_proto = out.File
	file_encore_parser_schema_v1_schema_proto_goTypes = nil
	file_encore_parser_schema_v1_schema_proto_depIdxs = nil
}
