body:
  - type: markdown
    attributes:
      value: |
        Check out our [documentation](https://encore.dev/docs) to see if your suggestion is already implemented.

        If you are not sure if your suggestion is a feature request you can ask a question on our [Discord community](https://encore.dev/discord).

        ---

  - type: checkboxes
    attributes:
      label: "Is there an existing discussion that is already proposing this?"
      description: "Please search [here](https://github.com/encoredev/encore/discussions) to see if a discussion already exists for the feature you are requesting"
      options:
      - label: "I have searched the existing discussions"
        required: true

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: "What part(s) of Encore does this feature request apply to?"
      options:
        - label: Encore.ts (TypeScript)
        - label: Encore.go (Go)
        - label: Encore CLI
        - label: Local Development Dashboard
        - label: Encore Cloud
        - label: Other

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Is your feature request related to a problem? Please describe it"
      description: "A clear and concise description of what the problem is"
      placeholder: |
        I have an issue when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen. Add any considered drawbacks"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "What is the motivation / use case for changing the behavior?"
      description: "Describe the motivation or the concrete use case"
