// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: encore/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment_Type int32

const (
	Environment_TYPE_UNSPECIFIED Environment_Type = 0
	Environment_TYPE_DEVELOPMENT Environment_Type = 1
	Environment_TYPE_PRODUCTION  Environment_Type = 2
	Environment_TYPE_EPHEMERAL   Environment_Type = 3
	Environment_TYPE_TEST        Environment_Type = 4
)

// Enum value maps for Environment_Type.
var (
	Environment_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_DEVELOPMENT",
		2: "TYPE_PRODUCTION",
		3: "TYPE_EPHEMERAL",
		4: "TYPE_TEST",
	}
	Environment_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_DEVELOPMENT": 1,
		"TYPE_PRODUCTION":  2,
		"TYPE_EPHEMERAL":   3,
		"TYPE_TEST":        4,
	}
)

func (x Environment_Type) Enum() *Environment_Type {
	p := new(Environment_Type)
	*p = x
	return p
}

func (x Environment_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_encore_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (Environment_Type) Type() protoreflect.EnumType {
	return &file_encore_runtime_v1_runtime_proto_enumTypes[0]
}

func (x Environment_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment_Type.Descriptor instead.
func (Environment_Type) EnumDescriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{1, 0}
}

type Environment_Cloud int32

const (
	Environment_CLOUD_UNSPECIFIED Environment_Cloud = 0
	Environment_CLOUD_LOCAL       Environment_Cloud = 1
	Environment_CLOUD_ENCORE      Environment_Cloud = 2
	Environment_CLOUD_AWS         Environment_Cloud = 3
	Environment_CLOUD_GCP         Environment_Cloud = 4
	Environment_CLOUD_AZURE       Environment_Cloud = 5
)

// Enum value maps for Environment_Cloud.
var (
	Environment_Cloud_name = map[int32]string{
		0: "CLOUD_UNSPECIFIED",
		1: "CLOUD_LOCAL",
		2: "CLOUD_ENCORE",
		3: "CLOUD_AWS",
		4: "CLOUD_GCP",
		5: "CLOUD_AZURE",
	}
	Environment_Cloud_value = map[string]int32{
		"CLOUD_UNSPECIFIED": 0,
		"CLOUD_LOCAL":       1,
		"CLOUD_ENCORE":      2,
		"CLOUD_AWS":         3,
		"CLOUD_GCP":         4,
		"CLOUD_AZURE":       5,
	}
)

func (x Environment_Cloud) Enum() *Environment_Cloud {
	p := new(Environment_Cloud)
	*p = x
	return p
}

func (x Environment_Cloud) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment_Cloud) Descriptor() protoreflect.EnumDescriptor {
	return file_encore_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (Environment_Cloud) Type() protoreflect.EnumType {
	return &file_encore_runtime_v1_runtime_proto_enumTypes[1]
}

func (x Environment_Cloud) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment_Cloud.Descriptor instead.
func (Environment_Cloud) EnumDescriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{1, 1}
}

type RuntimeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment    *Environment    `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Infra          *Infrastructure `protobuf:"bytes,2,opt,name=infra,proto3" json:"infra,omitempty"`
	Deployment     *Deployment     `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	EncorePlatform *EncorePlatform `protobuf:"bytes,5,opt,name=encore_platform,json=encorePlatform,proto3,oneof" json:"encore_platform,omitempty"`
}

func (x *RuntimeConfig) Reset() {
	*x = RuntimeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfig) ProtoMessage() {}

func (x *RuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfig.ProtoReflect.Descriptor instead.
func (*RuntimeConfig) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeConfig) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *RuntimeConfig) GetInfra() *Infrastructure {
	if x != nil {
		return x.Infra
	}
	return nil
}

func (x *RuntimeConfig) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *RuntimeConfig) GetEncorePlatform() *EncorePlatform {
	if x != nil {
		return x.EncorePlatform
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   string            `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSlug string            `protobuf:"bytes,2,opt,name=app_slug,json=appSlug,proto3" json:"app_slug,omitempty"`
	EnvId   string            `protobuf:"bytes,3,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	EnvName string            `protobuf:"bytes,4,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	EnvType Environment_Type  `protobuf:"varint,5,opt,name=env_type,json=envType,proto3,enum=encore.runtime.v1.Environment_Type" json:"env_type,omitempty"`
	Cloud   Environment_Cloud `protobuf:"varint,6,opt,name=cloud,proto3,enum=encore.runtime.v1.Environment_Cloud" json:"cloud,omitempty"`
}

func (x *Environment) Reset() {
	*x = Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Environment) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Environment) GetAppSlug() string {
	if x != nil {
		return x.AppSlug
	}
	return ""
}

func (x *Environment) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *Environment) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *Environment) GetEnvType() Environment_Type {
	if x != nil {
		return x.EnvType
	}
	return Environment_TYPE_UNSPECIFIED
}

func (x *Environment) GetCloud() Environment_Cloud {
	if x != nil {
		return x.Cloud
	}
	return Environment_CLOUD_UNSPECIFIED
}

// Describes the configuration related to a specific deployment,
// meaning a group of services deployed together (think a single k8s Deployment).
type Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeployId   string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	DeployedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	// A list of experiments to enable at runtime.
	DynamicExperiments []string `protobuf:"bytes,3,rep,name=dynamic_experiments,json=dynamicExperiments,proto3" json:"dynamic_experiments,omitempty"`
	// The gateways hosted by this deployment, by rid.
	HostedGateways []string `protobuf:"bytes,4,rep,name=hosted_gateways,json=hostedGateways,proto3" json:"hosted_gateways,omitempty"`
	// The services hosted by this deployment.
	HostedServices []*HostedService `protobuf:"bytes,5,rep,name=hosted_services,json=hostedServices,proto3" json:"hosted_services,omitempty"`
	// The authentication method(s) that can be used when talking
	// to this deployment for internal service-to-service calls.
	//
	// An empty list means no service-to-service calls can be made to this deployment.
	AuthMethods []*ServiceAuth `protobuf:"bytes,6,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	// Observability-related configuration.
	Observability *Observability `protobuf:"bytes,7,opt,name=observability,proto3" json:"observability,omitempty"`
	// Service discovery configuration.
	ServiceDiscovery *ServiceDiscovery `protobuf:"bytes,8,opt,name=service_discovery,json=serviceDiscovery,proto3" json:"service_discovery,omitempty"`
	// Graceful shutdown behavior.
	GracefulShutdown *GracefulShutdown `protobuf:"bytes,9,opt,name=graceful_shutdown,json=gracefulShutdown,proto3" json:"graceful_shutdown,omitempty"`
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Deployment) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *Deployment) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *Deployment) GetDynamicExperiments() []string {
	if x != nil {
		return x.DynamicExperiments
	}
	return nil
}

func (x *Deployment) GetHostedGateways() []string {
	if x != nil {
		return x.HostedGateways
	}
	return nil
}

func (x *Deployment) GetHostedServices() []*HostedService {
	if x != nil {
		return x.HostedServices
	}
	return nil
}

func (x *Deployment) GetAuthMethods() []*ServiceAuth {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

func (x *Deployment) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Deployment) GetServiceDiscovery() *ServiceDiscovery {
	if x != nil {
		return x.ServiceDiscovery
	}
	return nil
}

func (x *Deployment) GetGracefulShutdown() *GracefulShutdown {
	if x != nil {
		return x.GracefulShutdown
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The observability providers to use.
	Tracing []*TracingProvider `protobuf:"bytes,1,rep,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics []*MetricsProvider `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Logs    []*LogsProvider    `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *Observability) Reset() {
	*x = Observability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *Observability) GetTracing() []*TracingProvider {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Observability) GetMetrics() []*MetricsProvider {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Observability) GetLogs() []*LogsProvider {
	if x != nil {
		return x.Logs
	}
	return nil
}

type HostedService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the service.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of worker threads to use.
	// If unset it defaults to 1. If set to 0 the runtime
	// automatically determines the number of threads to use
	// based on the number of CPUs available.
	WorkerThreads *int32 `protobuf:"varint,2,opt,name=worker_threads,json=workerThreads,proto3,oneof" json:"worker_threads,omitempty"`
	// The log configuration to use for this service.
	// If unset it defaults to "trace".
	LogConfig *string `protobuf:"bytes,3,opt,name=log_config,json=logConfig,proto3,oneof" json:"log_config,omitempty"`
}

func (x *HostedService) Reset() {
	*x = HostedService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostedService) ProtoMessage() {}

func (x *HostedService) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostedService.ProtoReflect.Descriptor instead.
func (*HostedService) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *HostedService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostedService) GetWorkerThreads() int32 {
	if x != nil && x.WorkerThreads != nil {
		return *x.WorkerThreads
	}
	return 0
}

func (x *HostedService) GetLogConfig() string {
	if x != nil && x.LogConfig != nil {
		return *x.LogConfig
	}
	return ""
}

type ServiceAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The auth method to use.
	//
	// Types that are assignable to AuthMethod:
	//
	//	*ServiceAuth_Noop
	//	*ServiceAuth_EncoreAuth_
	AuthMethod isServiceAuth_AuthMethod `protobuf_oneof:"auth_method"`
}

func (x *ServiceAuth) Reset() {
	*x = ServiceAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuth) ProtoMessage() {}

func (x *ServiceAuth) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuth.ProtoReflect.Descriptor instead.
func (*ServiceAuth) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (m *ServiceAuth) GetAuthMethod() isServiceAuth_AuthMethod {
	if m != nil {
		return m.AuthMethod
	}
	return nil
}

func (x *ServiceAuth) GetNoop() *ServiceAuth_NoopAuth {
	if x, ok := x.GetAuthMethod().(*ServiceAuth_Noop); ok {
		return x.Noop
	}
	return nil
}

func (x *ServiceAuth) GetEncoreAuth() *ServiceAuth_EncoreAuth {
	if x, ok := x.GetAuthMethod().(*ServiceAuth_EncoreAuth_); ok {
		return x.EncoreAuth
	}
	return nil
}

type isServiceAuth_AuthMethod interface {
	isServiceAuth_AuthMethod()
}

type ServiceAuth_Noop struct {
	// Messages start at 10 to allow for other fields on ServiceAuth.
	Noop *ServiceAuth_NoopAuth `protobuf:"bytes,10,opt,name=noop,proto3,oneof"`
}

type ServiceAuth_EncoreAuth_ struct {
	EncoreAuth *ServiceAuth_EncoreAuth `protobuf:"bytes,11,opt,name=encore_auth,json=encoreAuth,proto3,oneof"`
}

func (*ServiceAuth_Noop) isServiceAuth_AuthMethod() {}

func (*ServiceAuth_EncoreAuth_) isServiceAuth_AuthMethod() {}

type TracingProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique resource id for this provider.
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// Types that are assignable to Provider:
	//
	//	*TracingProvider_Encore
	Provider isTracingProvider_Provider `protobuf_oneof:"provider"`
}

func (x *TracingProvider) Reset() {
	*x = TracingProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracingProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingProvider) ProtoMessage() {}

func (x *TracingProvider) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingProvider.ProtoReflect.Descriptor instead.
func (*TracingProvider) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *TracingProvider) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (m *TracingProvider) GetProvider() isTracingProvider_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *TracingProvider) GetEncore() *TracingProvider_EncoreTracingProvider {
	if x, ok := x.GetProvider().(*TracingProvider_Encore); ok {
		return x.Encore
	}
	return nil
}

type isTracingProvider_Provider interface {
	isTracingProvider_Provider()
}

type TracingProvider_Encore struct {
	Encore *TracingProvider_EncoreTracingProvider `protobuf:"bytes,10,opt,name=encore,proto3,oneof"`
}

func (*TracingProvider_Encore) isTracingProvider_Provider() {}

type MetricsProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique resource id for this provider.
	Rid                string               `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	CollectionInterval *durationpb.Duration `protobuf:"bytes,2,opt,name=collection_interval,json=collectionInterval,proto3" json:"collection_interval,omitempty"`
	// Types that are assignable to Provider:
	//
	//	*MetricsProvider_EncoreCloud
	//	*MetricsProvider_Gcp
	//	*MetricsProvider_Aws
	//	*MetricsProvider_PromRemoteWrite
	//	*MetricsProvider_Datadog_
	Provider isMetricsProvider_Provider `protobuf_oneof:"provider"`
}

func (x *MetricsProvider) Reset() {
	*x = MetricsProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsProvider) ProtoMessage() {}

func (x *MetricsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsProvider.ProtoReflect.Descriptor instead.
func (*MetricsProvider) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsProvider) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *MetricsProvider) GetCollectionInterval() *durationpb.Duration {
	if x != nil {
		return x.CollectionInterval
	}
	return nil
}

func (m *MetricsProvider) GetProvider() isMetricsProvider_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *MetricsProvider) GetEncoreCloud() *MetricsProvider_GCPCloudMonitoring {
	if x, ok := x.GetProvider().(*MetricsProvider_EncoreCloud); ok {
		return x.EncoreCloud
	}
	return nil
}

func (x *MetricsProvider) GetGcp() *MetricsProvider_GCPCloudMonitoring {
	if x, ok := x.GetProvider().(*MetricsProvider_Gcp); ok {
		return x.Gcp
	}
	return nil
}

func (x *MetricsProvider) GetAws() *MetricsProvider_AWSCloudWatch {
	if x, ok := x.GetProvider().(*MetricsProvider_Aws); ok {
		return x.Aws
	}
	return nil
}

func (x *MetricsProvider) GetPromRemoteWrite() *MetricsProvider_PrometheusRemoteWrite {
	if x, ok := x.GetProvider().(*MetricsProvider_PromRemoteWrite); ok {
		return x.PromRemoteWrite
	}
	return nil
}

func (x *MetricsProvider) GetDatadog() *MetricsProvider_Datadog {
	if x, ok := x.GetProvider().(*MetricsProvider_Datadog_); ok {
		return x.Datadog
	}
	return nil
}

type isMetricsProvider_Provider interface {
	isMetricsProvider_Provider()
}

type MetricsProvider_EncoreCloud struct {
	EncoreCloud *MetricsProvider_GCPCloudMonitoring `protobuf:"bytes,10,opt,name=encore_cloud,json=encoreCloud,proto3,oneof"`
}

type MetricsProvider_Gcp struct {
	Gcp *MetricsProvider_GCPCloudMonitoring `protobuf:"bytes,11,opt,name=gcp,proto3,oneof"`
}

type MetricsProvider_Aws struct {
	Aws *MetricsProvider_AWSCloudWatch `protobuf:"bytes,12,opt,name=aws,proto3,oneof"`
}

type MetricsProvider_PromRemoteWrite struct {
	PromRemoteWrite *MetricsProvider_PrometheusRemoteWrite `protobuf:"bytes,13,opt,name=prom_remote_write,json=promRemoteWrite,proto3,oneof"`
}

type MetricsProvider_Datadog_ struct {
	Datadog *MetricsProvider_Datadog `protobuf:"bytes,14,opt,name=datadog,proto3,oneof"`
}

func (*MetricsProvider_EncoreCloud) isMetricsProvider_Provider() {}

func (*MetricsProvider_Gcp) isMetricsProvider_Provider() {}

func (*MetricsProvider_Aws) isMetricsProvider_Provider() {}

func (*MetricsProvider_PromRemoteWrite) isMetricsProvider_Provider() {}

func (*MetricsProvider_Datadog_) isMetricsProvider_Provider() {}

type LogsProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique resource id for this provider.
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *LogsProvider) Reset() {
	*x = LogsProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsProvider) ProtoMessage() {}

func (x *LogsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsProvider.ProtoReflect.Descriptor instead.
func (*LogsProvider) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *LogsProvider) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type EncoreAuthKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *SecretData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EncoreAuthKey) Reset() {
	*x = EncoreAuthKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncoreAuthKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncoreAuthKey) ProtoMessage() {}

func (x *EncoreAuthKey) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncoreAuthKey.ProtoReflect.Descriptor instead.
func (*EncoreAuthKey) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *EncoreAuthKey) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EncoreAuthKey) GetData() *SecretData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Describes service discovery configuration.
type ServiceDiscovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Where services are located, keyed by the service name.
	Services map[string]*ServiceDiscovery_Location `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ServiceDiscovery) Reset() {
	*x = ServiceDiscovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscovery) ProtoMessage() {}

func (x *ServiceDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscovery.ProtoReflect.Descriptor instead.
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceDiscovery) GetServices() map[string]*ServiceDiscovery_Location {
	if x != nil {
		return x.Services
	}
	return nil
}

// GracefulShutdown defines the graceful shutdown timings.
type GracefulShutdown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total is how long we allow the total shutdown to take
	// before the process forcibly exits.
	Total *durationpb.Duration `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	// ShutdownHooks is how long before [total] runs out that we cancel
	// the context that is passed to the shutdown hooks.
	//
	// It is expected that ShutdownHooks is a larger value than Handlers.
	ShutdownHooks *durationpb.Duration `protobuf:"bytes,2,opt,name=shutdown_hooks,json=shutdownHooks,proto3" json:"shutdown_hooks,omitempty"`
	// Handlers is how long before [total] runs out that we cancel
	// the context that is passed to API and PubSub Subscription handlers.
	//
	// For example, if [total] is 10 seconds and [handlers] is 2 seconds,
	// then we will cancel the context passed to handlers 8 seconds after
	// a graceful shutdown is initiated.
	Handlers *durationpb.Duration `protobuf:"bytes,3,opt,name=handlers,proto3" json:"handlers,omitempty"`
}

func (x *GracefulShutdown) Reset() {
	*x = GracefulShutdown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GracefulShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulShutdown) ProtoMessage() {}

func (x *GracefulShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulShutdown.ProtoReflect.Descriptor instead.
func (*GracefulShutdown) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *GracefulShutdown) GetTotal() *durationpb.Duration {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *GracefulShutdown) GetShutdownHooks() *durationpb.Duration {
	if x != nil {
		return x.ShutdownHooks
	}
	return nil
}

func (x *GracefulShutdown) GetHandlers() *durationpb.Duration {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type EncorePlatform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Auth keys for validating signed requests from the Encore Platform.
	PlatformSigningKeys []*EncoreAuthKey `protobuf:"bytes,1,rep,name=platform_signing_keys,json=platformSigningKeys,proto3" json:"platform_signing_keys,omitempty"`
	// The Encore Cloud configuration to use, if running in Encore Cloud.
	EncoreCloud *EncoreCloudProvider `protobuf:"bytes,2,opt,name=encore_cloud,json=encoreCloud,proto3,oneof" json:"encore_cloud,omitempty"`
}

func (x *EncorePlatform) Reset() {
	*x = EncorePlatform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncorePlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncorePlatform) ProtoMessage() {}

func (x *EncorePlatform) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncorePlatform.ProtoReflect.Descriptor instead.
func (*EncorePlatform) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *EncorePlatform) GetPlatformSigningKeys() []*EncoreAuthKey {
	if x != nil {
		return x.PlatformSigningKeys
	}
	return nil
}

func (x *EncorePlatform) GetEncoreCloud() *EncoreCloudProvider {
	if x != nil {
		return x.EncoreCloud
	}
	return nil
}

type RateLimiter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*RateLimiter_TokenBucket_
	Kind isRateLimiter_Kind `protobuf_oneof:"kind"`
}

func (x *RateLimiter) Reset() {
	*x = RateLimiter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimiter) ProtoMessage() {}

func (x *RateLimiter) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimiter.ProtoReflect.Descriptor instead.
func (*RateLimiter) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (m *RateLimiter) GetKind() isRateLimiter_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *RateLimiter) GetTokenBucket() *RateLimiter_TokenBucket {
	if x, ok := x.GetKind().(*RateLimiter_TokenBucket_); ok {
		return x.TokenBucket
	}
	return nil
}

type isRateLimiter_Kind interface {
	isRateLimiter_Kind()
}

type RateLimiter_TokenBucket_ struct {
	TokenBucket *RateLimiter_TokenBucket `protobuf:"bytes,1,opt,name=token_bucket,json=tokenBucket,proto3,oneof"`
}

func (*RateLimiter_TokenBucket_) isRateLimiter_Kind() {}

type EncoreCloudProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique resource id for this provider.
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// URL to use to authenticate with the server.
	ServerUrl string           `protobuf:"bytes,2,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	AuthKeys  []*EncoreAuthKey `protobuf:"bytes,3,rep,name=auth_keys,json=authKeys,proto3" json:"auth_keys,omitempty"`
}

func (x *EncoreCloudProvider) Reset() {
	*x = EncoreCloudProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncoreCloudProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncoreCloudProvider) ProtoMessage() {}

func (x *EncoreCloudProvider) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncoreCloudProvider.ProtoReflect.Descriptor instead.
func (*EncoreCloudProvider) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *EncoreCloudProvider) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *EncoreCloudProvider) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *EncoreCloudProvider) GetAuthKeys() []*EncoreAuthKey {
	if x != nil {
		return x.AuthKeys
	}
	return nil
}

type ServiceAuth_NoopAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceAuth_NoopAuth) Reset() {
	*x = ServiceAuth_NoopAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAuth_NoopAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuth_NoopAuth) ProtoMessage() {}

func (x *ServiceAuth_NoopAuth) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuth_NoopAuth.ProtoReflect.Descriptor instead.
func (*ServiceAuth_NoopAuth) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{5, 0}
}

type ServiceAuth_EncoreAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthKeys []*EncoreAuthKey `protobuf:"bytes,1,rep,name=auth_keys,json=authKeys,proto3" json:"auth_keys,omitempty"`
}

func (x *ServiceAuth_EncoreAuth) Reset() {
	*x = ServiceAuth_EncoreAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAuth_EncoreAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuth_EncoreAuth) ProtoMessage() {}

func (x *ServiceAuth_EncoreAuth) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuth_EncoreAuth.ProtoReflect.Descriptor instead.
func (*ServiceAuth_EncoreAuth) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ServiceAuth_EncoreAuth) GetAuthKeys() []*EncoreAuthKey {
	if x != nil {
		return x.AuthKeys
	}
	return nil
}

type TracingProvider_EncoreTracingProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceEndpoint string `protobuf:"bytes,1,opt,name=trace_endpoint,json=traceEndpoint,proto3" json:"trace_endpoint,omitempty"`
	// The sampling rate to use for traces, between [0, 1].
	// If unset it defaults to 1 (meaning all requests are traced).
	SamplingRate *float64 `protobuf:"fixed64,2,opt,name=sampling_rate,json=samplingRate,proto3,oneof" json:"sampling_rate,omitempty"`
}

func (x *TracingProvider_EncoreTracingProvider) Reset() {
	*x = TracingProvider_EncoreTracingProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracingProvider_EncoreTracingProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingProvider_EncoreTracingProvider) ProtoMessage() {}

func (x *TracingProvider_EncoreTracingProvider) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingProvider_EncoreTracingProvider.ProtoReflect.Descriptor instead.
func (*TracingProvider_EncoreTracingProvider) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{6, 0}
}

func (x *TracingProvider_EncoreTracingProvider) GetTraceEndpoint() string {
	if x != nil {
		return x.TraceEndpoint
	}
	return ""
}

func (x *TracingProvider_EncoreTracingProvider) GetSamplingRate() float64 {
	if x != nil && x.SamplingRate != nil {
		return *x.SamplingRate
	}
	return 0
}

type MetricsProvider_GCPCloudMonitoring struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The GCP project id to send metrics to.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The enum value for the monitored resource this application is monitoring.
	// See https://cloud.google.com/monitoring/api/resources for valid values.
	MonitoredResourceType string `protobuf:"bytes,2,opt,name=monitored_resource_type,json=monitoredResourceType,proto3" json:"monitored_resource_type,omitempty"`
	// The labels to specify for the monitored resource.
	// Each monitored resource type has a pre-defined set of labels that must be set.
	// See https://cloud.google.com/monitoring/api/resources for expected labels.
	MonitoredResourceLabels map[string]string `protobuf:"bytes,3,rep,name=monitored_resource_labels,json=monitoredResourceLabels,proto3" json:"monitored_resource_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The mapping between metric names in Encore and metric names in GCP.
	MetricNames map[string]string `protobuf:"bytes,4,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MetricsProvider_GCPCloudMonitoring) Reset() {
	*x = MetricsProvider_GCPCloudMonitoring{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsProvider_GCPCloudMonitoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsProvider_GCPCloudMonitoring) ProtoMessage() {}

func (x *MetricsProvider_GCPCloudMonitoring) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsProvider_GCPCloudMonitoring.ProtoReflect.Descriptor instead.
func (*MetricsProvider_GCPCloudMonitoring) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MetricsProvider_GCPCloudMonitoring) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MetricsProvider_GCPCloudMonitoring) GetMonitoredResourceType() string {
	if x != nil {
		return x.MonitoredResourceType
	}
	return ""
}

func (x *MetricsProvider_GCPCloudMonitoring) GetMonitoredResourceLabels() map[string]string {
	if x != nil {
		return x.MonitoredResourceLabels
	}
	return nil
}

func (x *MetricsProvider_GCPCloudMonitoring) GetMetricNames() map[string]string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

type MetricsProvider_AWSCloudWatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The namespace to use for metrics.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *MetricsProvider_AWSCloudWatch) Reset() {
	*x = MetricsProvider_AWSCloudWatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsProvider_AWSCloudWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsProvider_AWSCloudWatch) ProtoMessage() {}

func (x *MetricsProvider_AWSCloudWatch) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsProvider_AWSCloudWatch.ProtoReflect.Descriptor instead.
func (*MetricsProvider_AWSCloudWatch) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{7, 1}
}

func (x *MetricsProvider_AWSCloudWatch) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type MetricsProvider_PrometheusRemoteWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The URL to send metrics to.
	RemoteWriteUrl *SecretData `protobuf:"bytes,1,opt,name=remote_write_url,json=remoteWriteUrl,proto3" json:"remote_write_url,omitempty"`
}

func (x *MetricsProvider_PrometheusRemoteWrite) Reset() {
	*x = MetricsProvider_PrometheusRemoteWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsProvider_PrometheusRemoteWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsProvider_PrometheusRemoteWrite) ProtoMessage() {}

func (x *MetricsProvider_PrometheusRemoteWrite) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsProvider_PrometheusRemoteWrite.ProtoReflect.Descriptor instead.
func (*MetricsProvider_PrometheusRemoteWrite) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{7, 2}
}

func (x *MetricsProvider_PrometheusRemoteWrite) GetRemoteWriteUrl() *SecretData {
	if x != nil {
		return x.RemoteWriteUrl
	}
	return nil
}

type MetricsProvider_Datadog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site   string      `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	ApiKey *SecretData `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *MetricsProvider_Datadog) Reset() {
	*x = MetricsProvider_Datadog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsProvider_Datadog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsProvider_Datadog) ProtoMessage() {}

func (x *MetricsProvider_Datadog) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsProvider_Datadog.ProtoReflect.Descriptor instead.
func (*MetricsProvider_Datadog) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{7, 3}
}

func (x *MetricsProvider_Datadog) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *MetricsProvider_Datadog) GetApiKey() *SecretData {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type ServiceDiscovery_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The base URL of the service (including scheme and port).
	BaseUrl string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// The auth methods to use when talking to this service.
	AuthMethods []*ServiceAuth `protobuf:"bytes,2,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
}

func (x *ServiceDiscovery_Location) Reset() {
	*x = ServiceDiscovery_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDiscovery_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscovery_Location) ProtoMessage() {}

func (x *ServiceDiscovery_Location) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscovery_Location.ProtoReflect.Descriptor instead.
func (*ServiceDiscovery_Location) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{10, 1}
}

func (x *ServiceDiscovery_Location) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ServiceDiscovery_Location) GetAuthMethods() []*ServiceAuth {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

type RateLimiter_TokenBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The rate (in events per per second) to allow.
	Rate float64 `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// The burst size to allow.
	Burst uint32 `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
}

func (x *RateLimiter_TokenBucket) Reset() {
	*x = RateLimiter_TokenBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encore_runtime_v1_runtime_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimiter_TokenBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimiter_TokenBucket) ProtoMessage() {}

func (x *RateLimiter_TokenBucket) ProtoReflect() protoreflect.Message {
	mi := &file_encore_runtime_v1_runtime_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimiter_TokenBucket.ProtoReflect.Descriptor instead.
func (*RateLimiter_TokenBucket) Descriptor() ([]byte, []int) {
	return file_encore_runtime_v1_runtime_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RateLimiter_TokenBucket) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RateLimiter_TokenBucket) GetBurst() uint32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

var File_encore_runtime_v1_runtime_proto protoreflect.FileDescriptor

var file_encore_runtime_v1_runtime_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x02, 0x0a, 0x0d, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x40, 0x0a, 0x0b, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x05,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x05,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x12, 0x3d, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x6e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4f, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x48, 0x00, 0x52, 0x0e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0xcb, 0x03, 0x0a, 0x0b, 0x45, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x76,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a,
	0x08, 0x65, 0x6e, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x23, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a,
	0x05, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x22, 0x6a, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x45, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x50, 0x48, 0x45, 0x4d,
	0x45, 0x52, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54,
	0x45, 0x53, 0x54, 0x10, 0x04, 0x22, 0x70, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x12, 0x15,
	0x0a, 0x11, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f, 0x4c,
	0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f,
	0x45, 0x4e, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x4f, 0x55,
	0x44, 0x5f, 0x41, 0x57, 0x53, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x4f, 0x55, 0x44,
	0x5f, 0x47, 0x43, 0x50, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f,
	0x41, 0x5a, 0x55, 0x52, 0x45, 0x10, 0x05, 0x22, 0xba, 0x04, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x2f, 0x0a, 0x13, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x6f, 0x73, 0x74,
	0x65, 0x64, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x49, 0x0a, 0x0f, 0x68, 0x6f,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52, 0x0b, 0x61, 0x75, 0x74,
	0x68, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x46, 0x0a, 0x0d, 0x6f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x0d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x50, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x12, 0x50, 0x0a, 0x11, 0x67, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x5f, 0x73,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x52, 0x10, 0x67, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74,
	0x64, 0x6f, 0x77, 0x6e, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x69, 0x6e, 0x67, 0x12, 0x3c, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x48, 0x6f, 0x73, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x09, 0x6c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a,
	0x0f, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x82, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x3d, 0x0a, 0x04, 0x6e, 0x6f, 0x6f, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x2e, 0x4e, 0x6f,
	0x6f, 0x70, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x6f, 0x70, 0x12, 0x4c,
	0x0a, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41,
	0x75, 0x74, 0x68, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00,
	0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x0a, 0x0a, 0x08,
	0x4e, 0x6f, 0x6f, 0x70, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x4b, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x6f,
	0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12, 0x3d, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x4b, 0x65, 0x79, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x22, 0xff, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x52, 0x0a, 0x06, 0x65, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x65, 0x6e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x7a,
	0x0a, 0x15, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x28,
	0x0a, 0x0d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x52, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0xf6, 0x09, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x4a, 0x0a, 0x13,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x5a, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x47, 0x43, 0x50, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x12, 0x49, 0x0a, 0x03, 0x67, 0x63, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x43, 0x50, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x03, 0x67, 0x63, 0x70, 0x12,
	0x44, 0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x41, 0x57, 0x53, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x77, 0x73, 0x12, 0x66, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x38, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x46, 0x0a,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x48, 0x00, 0x52, 0x07, 0x64, 0x61,
	0x74, 0x61, 0x64, 0x6f, 0x67, 0x1a, 0xf3, 0x03, 0x0a, 0x12, 0x47, 0x43, 0x50, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x6d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x8e, 0x01, 0x0a, 0x19, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x52, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x43, 0x50, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x17, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x12, 0x69, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x65, 0x6e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x47,
	0x43, 0x50, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x1a,
	0x4a, 0x0a, 0x1c, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3e, 0x0a, 0x10, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x2d, 0x0a, 0x0d, 0x41,
	0x57, 0x53, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x60, 0x0a, 0x15, 0x50, 0x72,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x1a, 0x55, 0x0a, 0x07,
	0x44, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x61,
	0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22,
	0x20, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69,
	0x64, 0x22, 0x52, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x4b,
	0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb6, 0x02, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x4d, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x69, 0x0a, 0x0d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x68, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x41, 0x0a, 0x0c, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0xbc,
	0x01, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x12, 0x2f, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x40, 0x0a, 0x0e, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e,
	0x5f, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x22, 0xc7, 0x01,
	0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x54, 0x0a, 0x15, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x73, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x65,
	0x79, 0x52, 0x13, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x69,
	0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x4e, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x12, 0x4f, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x37, 0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x75, 0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x75, 0x72, 0x73,
	0x74, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x45, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55,
	0x72, 0x6c, 0x12, 0x3d, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x72, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79,
	0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x65, 0x6e, 0x63, 0x72, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encore_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_encore_runtime_v1_runtime_proto_rawDescData = file_encore_runtime_v1_runtime_proto_rawDesc
)

func file_encore_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_encore_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_encore_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_encore_runtime_v1_runtime_proto_rawDescData)
	})
	return file_encore_runtime_v1_runtime_proto_rawDescData
}

var file_encore_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encore_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_encore_runtime_v1_runtime_proto_goTypes = []interface{}{
	(Environment_Type)(0),                         // 0: encore.runtime.v1.Environment.Type
	(Environment_Cloud)(0),                        // 1: encore.runtime.v1.Environment.Cloud
	(*RuntimeConfig)(nil),                         // 2: encore.runtime.v1.RuntimeConfig
	(*Environment)(nil),                           // 3: encore.runtime.v1.Environment
	(*Deployment)(nil),                            // 4: encore.runtime.v1.Deployment
	(*Observability)(nil),                         // 5: encore.runtime.v1.Observability
	(*HostedService)(nil),                         // 6: encore.runtime.v1.HostedService
	(*ServiceAuth)(nil),                           // 7: encore.runtime.v1.ServiceAuth
	(*TracingProvider)(nil),                       // 8: encore.runtime.v1.TracingProvider
	(*MetricsProvider)(nil),                       // 9: encore.runtime.v1.MetricsProvider
	(*LogsProvider)(nil),                          // 10: encore.runtime.v1.LogsProvider
	(*EncoreAuthKey)(nil),                         // 11: encore.runtime.v1.EncoreAuthKey
	(*ServiceDiscovery)(nil),                      // 12: encore.runtime.v1.ServiceDiscovery
	(*GracefulShutdown)(nil),                      // 13: encore.runtime.v1.GracefulShutdown
	(*EncorePlatform)(nil),                        // 14: encore.runtime.v1.EncorePlatform
	(*RateLimiter)(nil),                           // 15: encore.runtime.v1.RateLimiter
	(*EncoreCloudProvider)(nil),                   // 16: encore.runtime.v1.EncoreCloudProvider
	(*ServiceAuth_NoopAuth)(nil),                  // 17: encore.runtime.v1.ServiceAuth.NoopAuth
	(*ServiceAuth_EncoreAuth)(nil),                // 18: encore.runtime.v1.ServiceAuth.EncoreAuth
	(*TracingProvider_EncoreTracingProvider)(nil), // 19: encore.runtime.v1.TracingProvider.EncoreTracingProvider
	(*MetricsProvider_GCPCloudMonitoring)(nil),    // 20: encore.runtime.v1.MetricsProvider.GCPCloudMonitoring
	(*MetricsProvider_AWSCloudWatch)(nil),         // 21: encore.runtime.v1.MetricsProvider.AWSCloudWatch
	(*MetricsProvider_PrometheusRemoteWrite)(nil), // 22: encore.runtime.v1.MetricsProvider.PrometheusRemoteWrite
	(*MetricsProvider_Datadog)(nil),               // 23: encore.runtime.v1.MetricsProvider.Datadog
	nil,                                           // 24: encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.MonitoredResourceLabelsEntry
	nil,                                           // 25: encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.MetricNamesEntry
	nil,                                           // 26: encore.runtime.v1.ServiceDiscovery.ServicesEntry
	(*ServiceDiscovery_Location)(nil),             // 27: encore.runtime.v1.ServiceDiscovery.Location
	(*RateLimiter_TokenBucket)(nil),               // 28: encore.runtime.v1.RateLimiter.TokenBucket
	(*Infrastructure)(nil),                        // 29: encore.runtime.v1.Infrastructure
	(*timestamppb.Timestamp)(nil),                 // 30: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                   // 31: google.protobuf.Duration
	(*SecretData)(nil),                            // 32: encore.runtime.v1.SecretData
}
var file_encore_runtime_v1_runtime_proto_depIdxs = []int32{
	3,  // 0: encore.runtime.v1.RuntimeConfig.environment:type_name -> encore.runtime.v1.Environment
	29, // 1: encore.runtime.v1.RuntimeConfig.infra:type_name -> encore.runtime.v1.Infrastructure
	4,  // 2: encore.runtime.v1.RuntimeConfig.deployment:type_name -> encore.runtime.v1.Deployment
	14, // 3: encore.runtime.v1.RuntimeConfig.encore_platform:type_name -> encore.runtime.v1.EncorePlatform
	0,  // 4: encore.runtime.v1.Environment.env_type:type_name -> encore.runtime.v1.Environment.Type
	1,  // 5: encore.runtime.v1.Environment.cloud:type_name -> encore.runtime.v1.Environment.Cloud
	30, // 6: encore.runtime.v1.Deployment.deployed_at:type_name -> google.protobuf.Timestamp
	6,  // 7: encore.runtime.v1.Deployment.hosted_services:type_name -> encore.runtime.v1.HostedService
	7,  // 8: encore.runtime.v1.Deployment.auth_methods:type_name -> encore.runtime.v1.ServiceAuth
	5,  // 9: encore.runtime.v1.Deployment.observability:type_name -> encore.runtime.v1.Observability
	12, // 10: encore.runtime.v1.Deployment.service_discovery:type_name -> encore.runtime.v1.ServiceDiscovery
	13, // 11: encore.runtime.v1.Deployment.graceful_shutdown:type_name -> encore.runtime.v1.GracefulShutdown
	8,  // 12: encore.runtime.v1.Observability.tracing:type_name -> encore.runtime.v1.TracingProvider
	9,  // 13: encore.runtime.v1.Observability.metrics:type_name -> encore.runtime.v1.MetricsProvider
	10, // 14: encore.runtime.v1.Observability.logs:type_name -> encore.runtime.v1.LogsProvider
	17, // 15: encore.runtime.v1.ServiceAuth.noop:type_name -> encore.runtime.v1.ServiceAuth.NoopAuth
	18, // 16: encore.runtime.v1.ServiceAuth.encore_auth:type_name -> encore.runtime.v1.ServiceAuth.EncoreAuth
	19, // 17: encore.runtime.v1.TracingProvider.encore:type_name -> encore.runtime.v1.TracingProvider.EncoreTracingProvider
	31, // 18: encore.runtime.v1.MetricsProvider.collection_interval:type_name -> google.protobuf.Duration
	20, // 19: encore.runtime.v1.MetricsProvider.encore_cloud:type_name -> encore.runtime.v1.MetricsProvider.GCPCloudMonitoring
	20, // 20: encore.runtime.v1.MetricsProvider.gcp:type_name -> encore.runtime.v1.MetricsProvider.GCPCloudMonitoring
	21, // 21: encore.runtime.v1.MetricsProvider.aws:type_name -> encore.runtime.v1.MetricsProvider.AWSCloudWatch
	22, // 22: encore.runtime.v1.MetricsProvider.prom_remote_write:type_name -> encore.runtime.v1.MetricsProvider.PrometheusRemoteWrite
	23, // 23: encore.runtime.v1.MetricsProvider.datadog:type_name -> encore.runtime.v1.MetricsProvider.Datadog
	32, // 24: encore.runtime.v1.EncoreAuthKey.data:type_name -> encore.runtime.v1.SecretData
	26, // 25: encore.runtime.v1.ServiceDiscovery.services:type_name -> encore.runtime.v1.ServiceDiscovery.ServicesEntry
	31, // 26: encore.runtime.v1.GracefulShutdown.total:type_name -> google.protobuf.Duration
	31, // 27: encore.runtime.v1.GracefulShutdown.shutdown_hooks:type_name -> google.protobuf.Duration
	31, // 28: encore.runtime.v1.GracefulShutdown.handlers:type_name -> google.protobuf.Duration
	11, // 29: encore.runtime.v1.EncorePlatform.platform_signing_keys:type_name -> encore.runtime.v1.EncoreAuthKey
	16, // 30: encore.runtime.v1.EncorePlatform.encore_cloud:type_name -> encore.runtime.v1.EncoreCloudProvider
	28, // 31: encore.runtime.v1.RateLimiter.token_bucket:type_name -> encore.runtime.v1.RateLimiter.TokenBucket
	11, // 32: encore.runtime.v1.EncoreCloudProvider.auth_keys:type_name -> encore.runtime.v1.EncoreAuthKey
	11, // 33: encore.runtime.v1.ServiceAuth.EncoreAuth.auth_keys:type_name -> encore.runtime.v1.EncoreAuthKey
	24, // 34: encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.monitored_resource_labels:type_name -> encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.MonitoredResourceLabelsEntry
	25, // 35: encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.metric_names:type_name -> encore.runtime.v1.MetricsProvider.GCPCloudMonitoring.MetricNamesEntry
	32, // 36: encore.runtime.v1.MetricsProvider.PrometheusRemoteWrite.remote_write_url:type_name -> encore.runtime.v1.SecretData
	32, // 37: encore.runtime.v1.MetricsProvider.Datadog.api_key:type_name -> encore.runtime.v1.SecretData
	27, // 38: encore.runtime.v1.ServiceDiscovery.ServicesEntry.value:type_name -> encore.runtime.v1.ServiceDiscovery.Location
	7,  // 39: encore.runtime.v1.ServiceDiscovery.Location.auth_methods:type_name -> encore.runtime.v1.ServiceAuth
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_encore_runtime_v1_runtime_proto_init() }
func file_encore_runtime_v1_runtime_proto_init() {
	if File_encore_runtime_v1_runtime_proto != nil {
		return
	}
	file_encore_runtime_v1_infra_proto_init()
	file_encore_runtime_v1_secretdata_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_encore_runtime_v1_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Observability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostedService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracingProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncoreAuthKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDiscovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GracefulShutdown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncorePlatform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimiter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncoreCloudProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAuth_NoopAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAuth_EncoreAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracingProvider_EncoreTracingProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsProvider_GCPCloudMonitoring); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsProvider_AWSCloudWatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsProvider_PrometheusRemoteWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsProvider_Datadog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDiscovery_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encore_runtime_v1_runtime_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimiter_TokenBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_encore_runtime_v1_runtime_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_encore_runtime_v1_runtime_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_encore_runtime_v1_runtime_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ServiceAuth_Noop)(nil),
		(*ServiceAuth_EncoreAuth_)(nil),
	}
	file_encore_runtime_v1_runtime_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*TracingProvider_Encore)(nil),
	}
	file_encore_runtime_v1_runtime_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*MetricsProvider_EncoreCloud)(nil),
		(*MetricsProvider_Gcp)(nil),
		(*MetricsProvider_Aws)(nil),
		(*MetricsProvider_PromRemoteWrite)(nil),
		(*MetricsProvider_Datadog_)(nil),
	}
	file_encore_runtime_v1_runtime_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_encore_runtime_v1_runtime_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*RateLimiter_TokenBucket_)(nil),
	}
	file_encore_runtime_v1_runtime_proto_msgTypes[17].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encore_runtime_v1_runtime_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encore_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_encore_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_encore_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_encore_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_encore_runtime_v1_runtime_proto = out.File
	file_encore_runtime_v1_runtime_proto_rawDesc = nil
	file_encore_runtime_v1_runtime_proto_goTypes = nil
	file_encore_runtime_v1_runtime_proto_depIdxs = nil
}
