// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: encore/ecl/v1/ecl.proto

package eclv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValueSource says where a resolved value came from.
type ValueSource int32

const (
	ValueSource_VALUE_SOURCE_UNSPECIFIED ValueSource = 0
	ValueSource_VALUE_SOURCE_EXPLICIT    ValueSource = 1 // configured on the resource itself
	ValueSource_VALUE_SOURCE_DEFAULT     ValueSource = 2 // applied from a rule default (or exact-value default)
)

// Enum value maps for ValueSource.
var (
	ValueSource_name = map[int32]string{
		0: "VALUE_SOURCE_UNSPECIFIED",
		1: "VALUE_SOURCE_EXPLICIT",
		2: "VALUE_SOURCE_DEFAULT",
	}
	ValueSource_value = map[string]int32{
		"VALUE_SOURCE_UNSPECIFIED": 0,
		"VALUE_SOURCE_EXPLICIT":    1,
		"VALUE_SOURCE_DEFAULT":     2,
	}
)

func (x ValueSource) Enum() *ValueSource {
	p := new(ValueSource)
	*p = x
	return p
}

func (x ValueSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueSource) Descriptor() protoreflect.EnumDescriptor {
	return file_encore_ecl_v1_ecl_proto_enumTypes[0].Descriptor()
}

func (ValueSource) Type() protoreflect.EnumType {
	return &file_encore_ecl_v1_ecl_proto_enumTypes[0]
}

func (x ValueSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueSource.Descriptor instead.
func (ValueSource) EnumDescriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{0}
}

// EvaluationResult is the output of evaluating an ECL policy set against an
// environment: the resolved configuration for every resource, with the
// effective constraints the resolved values satisfy.
type EvaluationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResult) Reset() {
	*x = EvaluationResult{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResult) ProtoMessage() {}

func (x *EvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResult.ProtoReflect.Descriptor instead.
func (*EvaluationResult) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluationResult) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// Resource is one evaluated infrastructure resource.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // resource kind, e.g. "service", "sql_cluster"
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // resource name, e.g. "api", "main"
	// managed is true if ECL instantiates this resource (a managed kind such as
	// sql_cluster); false if it only configures a resource discovered from the
	// application (such as service).
	Managed bool `protobuf:"varint,3,opt,name=managed,proto3" json:"managed,omitempty"`
	// properties holds the resolved scalar configuration: explicitly-set values
	// plus applied defaults, each with the effective constraint it satisfies.
	Properties []*Property `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty"`
	// references holds the reference-valued properties, each resolved to a target
	// resource (and any constraints that target must satisfy).
	References    []*Reference `protobuf:"bytes,5,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *Resource) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Resource) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

// Property is one resolved scalar property of a resource.
type Property struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Path   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                     // dotted property path, e.g. "cpu", "instances.min"
	Value  *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                   // the resolved value
	Source ValueSource            `protobuf:"varint,3,opt,name=source,proto3,enum=encore.ecl.v1.ValueSource" json:"source,omitempty"` // where the value came from
	// constraint is the effective constraint the value must satisfy, merged from
	// every rule that matched the resource. Unset if no rule constrains it.
	Constraint    *Constraint `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{2}
}

func (x *Property) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Property) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Property) GetSource() ValueSource {
	if x != nil {
		return x.Source
	}
	return ValueSource_VALUE_SOURCE_UNSPECIFIED
}

func (x *Property) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

// Value is a resolved ECL value. Sizes are canonical bytes and durations are
// canonical milliseconds; `unit` carries the original display unit.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_StringValue
	//	*Value_SizeBytes
	//	*Value_DurationMs
	Kind isValue_Kind `protobuf_oneof:"kind"`
	// unit is the display unit for sizes/durations (e.g. "Gi", "d"); empty means
	// choose one automatically. Ignored for number/bool/string.
	Unit          string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetSizeBytes() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_SizeBytes); ok {
			return x.SizeBytes
		}
	}
	return 0
}

func (x *Value) GetDurationMs() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DurationMs); ok {
			return x.DurationMs
		}
	}
	return 0
}

func (x *Value) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_SizeBytes struct {
	SizeBytes float64 `protobuf:"fixed64,4,opt,name=size_bytes,json=sizeBytes,proto3,oneof"` // size in bytes
}

type Value_DurationMs struct {
	DurationMs float64 `protobuf:"fixed64,5,opt,name=duration_ms,json=durationMs,proto3,oneof"` // duration in milliseconds
}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_SizeBytes) isValue_Kind() {}

func (*Value_DurationMs) isValue_Kind() {}

// Constraint is the effective, merged constraint on a property: the
// intersection of the constraints from every matching rule, normalized into
// bounds and value sets. Shapes that don't normalize (e.g. a disjunction
// containing ranges) are represented only by `expr`.
type Constraint struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Required bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"` // the property must be set
	Min      *Bound                 `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`            // lower bound (>= / >); absent if none
	Max      *Bound                 `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`            // upper bound (<= / <); absent if none
	Allowed  []*Value               `protobuf:"bytes,4,rep,name=allowed,proto3" json:"allowed,omitempty"`    // allowed values (== or `in [...]`); empty if unconstrained
	Excluded []*Value               `protobuf:"bytes,5,rep,name=excluded,proto3" json:"excluded,omitempty"`  // disallowed values (!=)
	// expr is the effective constraint rendered as ECL source text, e.g.
	// ">= 1 & <= 4". Set whenever a constraint exists; the authoritative form when
	// the structured fields above cannot represent it.
	Expr          string `protobuf:"bytes,6,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{4}
}

func (x *Constraint) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Constraint) GetMin() *Bound {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Constraint) GetMax() *Bound {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Constraint) GetAllowed() []*Value {
	if x != nil {
		return x.Allowed
	}
	return nil
}

func (x *Constraint) GetExcluded() []*Value {
	if x != nil {
		return x.Excluded
	}
	return nil
}

func (x *Constraint) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// Bound is one side of a numeric/size/duration range.
type Bound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Inclusive     bool                   `protobuf:"varint,2,opt,name=inclusive,proto3" json:"inclusive,omitempty"` // true for >= / <=, false for > / <
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bound) Reset() {
	*x = Bound{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bound) ProtoMessage() {}

func (x *Bound) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bound.ProtoReflect.Descriptor instead.
func (*Bound) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{5}
}

func (x *Bound) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Bound) GetInclusive() bool {
	if x != nil {
		return x.Inclusive
	}
	return false
}

// Reference is a reference-valued property resolved to a target resource.
type Reference struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Path       string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                               // property path holding the reference, e.g. "cluster"
	TargetKind string                 `protobuf:"bytes,2,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"` // referenced resource kind, e.g. "sql_cluster"
	TargetName string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"` // resolved target name; empty if unresolved
	// unresolved is the reason the reference could not be resolved; empty on
	// success.
	Unresolved string `protobuf:"bytes,4,opt,name=unresolved,proto3" json:"unresolved,omitempty"`
	// object holds constraints the target resource must satisfy, from nested
	// object syntax (e.g. `cluster: sql_cluster.main & { backup_retention: >= 90d }`).
	Object        []*PropertyConstraint `protobuf:"bytes,5,rep,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{6}
}

func (x *Reference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Reference) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *Reference) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *Reference) GetUnresolved() string {
	if x != nil {
		return x.Unresolved
	}
	return ""
}

func (x *Reference) GetObject() []*PropertyConstraint {
	if x != nil {
		return x.Object
	}
	return nil
}

// PropertyConstraint is a constraint on a (referenced) resource's property,
// without a resolved value.
type PropertyConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Constraint    *Constraint            `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyConstraint) Reset() {
	*x = PropertyConstraint{}
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyConstraint) ProtoMessage() {}

func (x *PropertyConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_encore_ecl_v1_ecl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyConstraint.ProtoReflect.Descriptor instead.
func (*PropertyConstraint) Descriptor() ([]byte, []int) {
	return file_encore_ecl_v1_ecl_proto_rawDescGZIP(), []int{7}
}

func (x *PropertyConstraint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PropertyConstraint) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

var File_encore_ecl_v1_ecl_proto protoreflect.FileDescriptor

const file_encore_ecl_v1_ecl_proto_rawDesc = "" +
	"\n" +
	"\x17encore/ecl/v1/ecl.proto\x12\rencore.ecl.v1\"I\n" +
	"\x10EvaluationResult\x125\n" +
	"\tresources\x18\x01 \x03(\v2\x17.encore.ecl.v1.ResourceR\tresources\"\xbf\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amanaged\x18\x03 \x01(\bR\amanaged\x127\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2\x17.encore.ecl.v1.PropertyR\n" +
	"properties\x128\n" +
	"\n" +
	"references\x18\x05 \x03(\v2\x18.encore.ecl.v1.ReferenceR\n" +
	"references\"\xb9\x01\n" +
	"\bProperty\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.encore.ecl.v1.ValueR\x05value\x122\n" +
	"\x06source\x18\x03 \x01(\x0e2\x1a.encore.ecl.v1.ValueSourceR\x06source\x129\n" +
	"\n" +
	"constraint\x18\x04 \x01(\v2\x19.encore.ecl.v1.ConstraintR\n" +
	"constraint\"\xd2\x01\n" +
	"\x05Value\x12#\n" +
	"\fnumber_value\x18\x01 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x01H\x00R\tsizeBytes\x12!\n" +
	"\vduration_ms\x18\x05 \x01(\x01H\x00R\n" +
	"durationMs\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unitB\x06\n" +
	"\x04kind\"\xee\x01\n" +
	"\n" +
	"Constraint\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12&\n" +
	"\x03min\x18\x02 \x01(\v2\x14.encore.ecl.v1.BoundR\x03min\x12&\n" +
	"\x03max\x18\x03 \x01(\v2\x14.encore.ecl.v1.BoundR\x03max\x12.\n" +
	"\aallowed\x18\x04 \x03(\v2\x14.encore.ecl.v1.ValueR\aallowed\x120\n" +
	"\bexcluded\x18\x05 \x03(\v2\x14.encore.ecl.v1.ValueR\bexcluded\x12\x12\n" +
	"\x04expr\x18\x06 \x01(\tR\x04expr\"Q\n" +
	"\x05Bound\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.encore.ecl.v1.ValueR\x05value\x12\x1c\n" +
	"\tinclusive\x18\x02 \x01(\bR\tinclusive\"\xbc\x01\n" +
	"\tReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vtarget_kind\x18\x02 \x01(\tR\n" +
	"targetKind\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\x12\x1e\n" +
	"\n" +
	"unresolved\x18\x04 \x01(\tR\n" +
	"unresolved\x129\n" +
	"\x06object\x18\x05 \x03(\v2!.encore.ecl.v1.PropertyConstraintR\x06object\"c\n" +
	"\x12PropertyConstraint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x129\n" +
	"\n" +
	"constraint\x18\x02 \x01(\v2\x19.encore.ecl.v1.ConstraintR\n" +
	"constraint*`\n" +
	"\vValueSource\x12\x1c\n" +
	"\x18VALUE_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15VALUE_SOURCE_EXPLICIT\x10\x01\x12\x18\n" +
	"\x14VALUE_SOURCE_DEFAULT\x10\x02B$Z\"encr.dev/proto/encore/ecl/v1;eclv1b\x06proto3"

var (
	file_encore_ecl_v1_ecl_proto_rawDescOnce sync.Once
	file_encore_ecl_v1_ecl_proto_rawDescData []byte
)

func file_encore_ecl_v1_ecl_proto_rawDescGZIP() []byte {
	file_encore_ecl_v1_ecl_proto_rawDescOnce.Do(func() {
		file_encore_ecl_v1_ecl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encore_ecl_v1_ecl_proto_rawDesc), len(file_encore_ecl_v1_ecl_proto_rawDesc)))
	})
	return file_encore_ecl_v1_ecl_proto_rawDescData
}

var file_encore_ecl_v1_ecl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_encore_ecl_v1_ecl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_encore_ecl_v1_ecl_proto_goTypes = []any{
	(ValueSource)(0),           // 0: encore.ecl.v1.ValueSource
	(*EvaluationResult)(nil),   // 1: encore.ecl.v1.EvaluationResult
	(*Resource)(nil),           // 2: encore.ecl.v1.Resource
	(*Property)(nil),           // 3: encore.ecl.v1.Property
	(*Value)(nil),              // 4: encore.ecl.v1.Value
	(*Constraint)(nil),         // 5: encore.ecl.v1.Constraint
	(*Bound)(nil),              // 6: encore.ecl.v1.Bound
	(*Reference)(nil),          // 7: encore.ecl.v1.Reference
	(*PropertyConstraint)(nil), // 8: encore.ecl.v1.PropertyConstraint
}
var file_encore_ecl_v1_ecl_proto_depIdxs = []int32{
	2,  // 0: encore.ecl.v1.EvaluationResult.resources:type_name -> encore.ecl.v1.Resource
	3,  // 1: encore.ecl.v1.Resource.properties:type_name -> encore.ecl.v1.Property
	7,  // 2: encore.ecl.v1.Resource.references:type_name -> encore.ecl.v1.Reference
	4,  // 3: encore.ecl.v1.Property.value:type_name -> encore.ecl.v1.Value
	0,  // 4: encore.ecl.v1.Property.source:type_name -> encore.ecl.v1.ValueSource
	5,  // 5: encore.ecl.v1.Property.constraint:type_name -> encore.ecl.v1.Constraint
	6,  // 6: encore.ecl.v1.Constraint.min:type_name -> encore.ecl.v1.Bound
	6,  // 7: encore.ecl.v1.Constraint.max:type_name -> encore.ecl.v1.Bound
	4,  // 8: encore.ecl.v1.Constraint.allowed:type_name -> encore.ecl.v1.Value
	4,  // 9: encore.ecl.v1.Constraint.excluded:type_name -> encore.ecl.v1.Value
	4,  // 10: encore.ecl.v1.Bound.value:type_name -> encore.ecl.v1.Value
	8,  // 11: encore.ecl.v1.Reference.object:type_name -> encore.ecl.v1.PropertyConstraint
	5,  // 12: encore.ecl.v1.PropertyConstraint.constraint:type_name -> encore.ecl.v1.Constraint
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_encore_ecl_v1_ecl_proto_init() }
func file_encore_ecl_v1_ecl_proto_init() {
	if File_encore_ecl_v1_ecl_proto != nil {
		return
	}
	file_encore_ecl_v1_ecl_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_SizeBytes)(nil),
		(*Value_DurationMs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encore_ecl_v1_ecl_proto_rawDesc), len(file_encore_ecl_v1_ecl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encore_ecl_v1_ecl_proto_goTypes,
		DependencyIndexes: file_encore_ecl_v1_ecl_proto_depIdxs,
		EnumInfos:         file_encore_ecl_v1_ecl_proto_enumTypes,
		MessageInfos:      file_encore_ecl_v1_ecl_proto_msgTypes,
	}.Build()
	File_encore_ecl_v1_ecl_proto = out.File
	file_encore_ecl_v1_ecl_proto_goTypes = nil
	file_encore_ecl_v1_ecl_proto_depIdxs = nil
}
