// Code generated by "stringer -type=Kind -output=resource_string.go"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[PubSubTopic-1]
	_ = x[PubSubSubscription-2]
	_ = x[SQLDatabase-3]
	_ = x[Metric-4]
	_ = x[CronJob-5]
	_ = x[CacheCluster-6]
	_ = x[CacheKeyspace-7]
	_ = x[ConfigLoad-8]
	_ = x[Secrets-9]
	_ = x[Bucket-10]
	_ = x[APIEndpoint-11]
	_ = x[AuthHandler-12]
	_ = x[Middleware-13]
	_ = x[ServiceStruct-14]
}

const _Kind_name = "UnknownPubSubTopicPubSubSubscriptionSQLDatabaseMetricCronJobCacheClusterCacheKeyspaceConfigLoadSecretsBucketAPIEndpointAuthHandlerMiddlewareServiceStruct"

var _Kind_index = [...]uint8{0, 7, 18, 36, 47, 53, 60, 72, 85, 95, 102, 108, 119, 130, 140, 153}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
