[package]
name = "litparser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
duration-string = "0.3.0"
swc_ecma_ast = "0.110.9"
swc_common = { version = "0.33.8", features = ["tty-emitter"] }
clean-path = "0.2.1"
num-bigint = "0.4.5"
num-integer = "0.1.46"
num-traits = "0.2.19"
